<TeXmacs|2.1.5>

<style|<tuple|source|std>>

<\body>
  <active*|<\src-title>
    <src-package|git-pages|1.0>

    <\src-purpose>
      Internal style package for the pages generated by the Git tools.
    </src-purpose>

    <src-copyright|2026|Massimiliano Gubinelli>

    <\src-license>
      This software falls under the <hlink|GNU general public license,
      version 3 or later|$TEXMACS_PATH/LICENSE>. It comes WITHOUT ANY
      WARRANTY WHATSOEVER. You should have received a copy of the license
      which the software. If not, see <hlink|http://www.gnu.org/licenses/gpl-3.0.html|http://www.gnu.org/licenses/gpl-3.0.html>.
    </src-license>
  </src-title>>

  <\active*>
    <\src-comment>
      Buttons (inside action tags), status badges and muted text.
    </src-comment>
  </active*>

  <assign|git-button|<macro|body|<small|<with|ornament-color|#e8e8ec|ornament-sunny-color|#f6f6f8|ornament-shadow-color|#b8b8c0|ornament-hpadding|0.5spc|ornament-vpadding|0.25ex|ornament-border|1ln|<ornament|<arg|body>>>>>>

  <assign|git-badge|<macro|kind|body|<small|<with|font-series|bold|color|<case|<equal|<arg|kind>|conflict>|#b01010|<equal|<arg|kind>|staged>|#207020|<equal|<arg|kind>|new>|#2040a0|#707070>|<arg|body>>>>>

  <assign|git-muted|<macro|body|<with|color|#707070|<arg|body>>>>

  <assign|git-note|<macro|color|body|<small|<with|color|<arg|color>|<arg|body>>>>>

  <drd-props|git-button|arity|1>

  <drd-props|git-badge|arity|2>

  <drd-props|git-muted|arity|1>

  <drd-props|git-note|arity|2>

  \;
</body>

<\initial>
  <\collection>
    <associate|preamble|true>
  </collection>
</initial>
