include(CheckTypeSize)
include(CheckIncludeFiles)
include(CheckIncludeFile)
include(CheckFunctionExists)
include(CheckSymbolExists)
include(CheckStructHasMember)
include(CheckCSourceCompiles)

# Package variables
set(PACKAGE_BUGREPORT "bugs@texmacs.org")
set(PACKAGE_NAME "guile-texmacs")
set(PACKAGE_STRING "guile-texmacs 1.8.8")
set(PACKAGE_TARNAME "guile-texmacs")
set(PACKAGE_URL "")
set(PACKAGE_VERSION "1.8.8")

if(WIN32)
    list(APPEND CMAKE_REQUIRED_LIBRARIES ws2_32)
endif()

# Check for regex library
find_path(REGEX_INCLUDE_DIR NAMES regex.h PATHS "C:/msys64/mingw64/include" "/mingw64/include")
find_library(REGEX_LIBRARY NAMES regex PATHS "C:/msys64/mingw64/lib" "/mingw64/lib")
if(REGEX_INCLUDE_DIR AND REGEX_LIBRARY)
    set(HAVE_REGEX_H 1)
    set(HAVE_REGCOMP 1)
    set(HAVE_LIBREGEX 1)
    set(REGEX_LIBRARIES ${REGEX_LIBRARY})
else()
    check_include_file("regex.h" HAVE_REGEX_H)
    check_function_exists("regcomp" HAVE_REGCOMP)
    set(REGEX_LIBRARIES "")
endif()

# 1. Type sizes
check_type_size("char" SIZEOF_CHAR)
check_type_size("unsigned char" SIZEOF_UNSIGNED_CHAR)
check_type_size("short" SIZEOF_SHORT)
check_type_size("unsigned short" SIZEOF_UNSIGNED_SHORT)
check_type_size("int" SIZEOF_INT)
check_type_size("unsigned int" SIZEOF_UNSIGNED_INT)
check_type_size("long" SIZEOF_LONG)
check_type_size("unsigned long" SIZEOF_UNSIGNED_LONG)
check_type_size("long long" SIZEOF_LONG_LONG)
check_type_size("unsigned long long" SIZEOF_UNSIGNED_LONG_LONG)
check_type_size("__int64" SIZEOF___INT64)
check_type_size("unsigned __int64" SIZEOF_UNSIGNED___INT64)
check_type_size("void*" SIZEOF_VOID_P)
check_type_size("size_t" SIZEOF_SIZE_T)
check_type_size("off_t" SIZEOF_OFF_T)
check_type_size("ptrdiff_t" SIZEOF_PTRDIFF_T)
check_type_size("intmax_t" SIZEOF_INTMAX_T)
check_type_size("intptr_t" SIZEOF_INTPTR_T)
check_type_size("uintptr_t" SIZEOF_UINTPTR_T)
check_type_size("float" SIZEOF_FLOAT)

# Set corresponding autoconf-named variables for scmconfig.h.in
macro(SET_SCM_SIZE var val)
    if(DEFINED ${val} AND NOT "${${val}}" STREQUAL "")
        set(${var} ${${val}})
    else()
        set(${var} 0)
    endif()
endmacro()

SET_SCM_SIZE(ac_cv_sizeof_char SIZEOF_CHAR)
SET_SCM_SIZE(ac_cv_sizeof_unsigned_char SIZEOF_UNSIGNED_CHAR)
SET_SCM_SIZE(ac_cv_sizeof_short SIZEOF_SHORT)
SET_SCM_SIZE(ac_cv_sizeof_unsigned_short SIZEOF_UNSIGNED_SHORT)
SET_SCM_SIZE(ac_cv_sizeof_int SIZEOF_INT)
SET_SCM_SIZE(ac_cv_sizeof_unsigned_int SIZEOF_UNSIGNED_INT)
SET_SCM_SIZE(ac_cv_sizeof_long SIZEOF_LONG)
SET_SCM_SIZE(ac_cv_sizeof_unsigned_long SIZEOF_UNSIGNED_LONG)
SET_SCM_SIZE(ac_cv_sizeof_long_long SIZEOF_LONG_LONG)
SET_SCM_SIZE(ac_cv_sizeof_unsigned_long_long SIZEOF_UNSIGNED_LONG_LONG)
SET_SCM_SIZE(ac_cv_sizeof___int64 SIZEOF___INT64)
SET_SCM_SIZE(ac_cv_sizeof_unsigned___int64 SIZEOF_UNSIGNED___INT64)
SET_SCM_SIZE(ac_cv_sizeof_void_p SIZEOF_VOID_P)
SET_SCM_SIZE(ac_cv_sizeof_size_t SIZEOF_SIZE_T)
SET_SCM_SIZE(ac_cv_sizeof_off_t SIZEOF_OFF_T)
SET_SCM_SIZE(ac_cv_sizeof_ptrdiff_t SIZEOF_PTRDIFF_T)
SET_SCM_SIZE(ac_cv_sizeof_intmax_t SIZEOF_INTMAX_T)
SET_SCM_SIZE(ac_cv_sizeof_intptr_t SIZEOF_INTPTR_T)
SET_SCM_SIZE(ac_cv_sizeof_uintptr_t SIZEOF_UINTPTR_T)
SET_SCM_SIZE(ac_cv_sizeof_float SIZEOF_FLOAT)

# 2. Header checks
check_include_file("stdint.h" HAVE_STDINT_H)
check_include_file("inttypes.h" HAVE_INTTYPES_H)
check_include_file("limits.h" HAVE_LIMITS_H)
check_include_file("stdlib.h" HAVE_STDLIB_H)
check_include_file("stddef.h" HAVE_STDDEF_H)
check_include_file("string.h" HAVE_STRING_H)
check_include_file("strings.h" HAVE_STRINGS_H)
check_include_file("memory.h" HAVE_MEMORY_H)
check_include_file("unistd.h" HAVE_UNISTD_H)
check_include_file("sys/types.h" HAVE_SYS_TYPES_H)
check_include_file("sys/stat.h" HAVE_SYS_STAT_H)
check_include_file("sys/time.h" HAVE_SYS_TIME_H)
check_include_file("time.h" HAVE_TIME_H)
check_include_file("sys/select.h" HAVE_SYS_SELECT_H)
check_include_file("sys/stdtypes.h" HAVE_SYS_STDTYPES_H)
check_include_file("sys/file.h" HAVE_SYS_FILE_H)
check_include_file("sys/ioctl.h" HAVE_SYS_IOCTL_H)
check_include_file("sys/resource.h" HAVE_SYS_RESOURCE_H)
check_include_file("sys/times.h" HAVE_SYS_TIMES_H)
check_include_file("sys/timeb.h" HAVE_SYS_TIMEB_H)
check_include_file("sys/utsname.h" HAVE_SYS_UTSNAME_H)
check_include_file("sys/wait.h" HAVE_SYS_WAIT_H)
check_include_file("direct.h" HAVE_DIRECT_H)
check_include_file("dirent.h" HAVE_DIRENT_H)
check_include_file("io.h" HAVE_IO_H)
check_include_file("process.h" HAVE_PROCESS_H)
check_include_file("winsock2.h" HAVE_WINSOCK2_H)
check_include_file("windows.h" HAVE_WINDOWS_H)
check_include_file("dlfcn.h" HAVE_DLFCN_H)
check_include_file("complex.h" HAVE_COMPLEX_H)
check_include_file("fenv.h" HAVE_FENV_H)
check_include_file("floatingpoint.h" HAVE_FLOATINGPOINT_H)
check_include_file("ieeefp.h" HAVE_IEEEFP_H)
check_include_file("nan.h" HAVE_NAN_H)
check_include_file("netdb.h" HAVE_NETDB_H)
check_include_file("pwd.h" HAVE_PWD_H)
check_include_file("grp.h" HAVE_GRP_H)
check_include_file("regex.h" HAVE_REGEX_H)
check_include_file("utime.h" HAVE_UTIME_H)
check_include_file("assert.h" HAVE_ASSERT_H)
check_include_file("alloca.h" HAVE_ALLOCA_H)
check_include_file("crt_externs.h" HAVE_CRT_EXTERNS_H)
check_include_file("crypt.h" HAVE_CRYPT_H)

# 3. Function checks
check_function_exists("acosh" HAVE_ACOSH)
check_function_exists("alloca" HAVE_ALLOCA)
check_function_exists("asinh" HAVE_ASINH)
check_function_exists("atanh" HAVE_ATANH)
check_function_exists("atexit" HAVE_ATEXIT)
check_function_exists("bcopy" HAVE_BCOPY)
check_function_exists("cexp" HAVE_CEXP)
check_function_exists("chown" HAVE_CHOWN)
check_function_exists("chroot" HAVE_CHROOT)
if(HAVE_WINSOCK2_H)
    check_symbol_exists(connect "winsock2.h" HAVE_CONNECT)
    check_symbol_exists(gethostbyname "winsock2.h" HAVE_GETHOSTBYNAME)
    check_symbol_exists(gethostname "winsock2.h" HAVE_GETHOSTNAME)
endif()
if(NOT HAVE_CONNECT)
    check_function_exists("connect" HAVE_CONNECT)
endif()
check_function_exists("copysign" HAVE_COPYSIGN)
check_function_exists("crypt" HAVE_CRYPT)
check_function_exists("ctermid" HAVE_CTERMID)
check_function_exists("cuserid" HAVE_CUSERID)
check_function_exists("fchmod" HAVE_FCHMOD)
check_function_exists("fchown" HAVE_FCHOWN)
check_function_exists("fcntl" HAVE_FCNTL)
check_function_exists("fesetround" HAVE_FESETROUND)
check_function_exists("finite" HAVE_FINITE)
check_function_exists("flock" HAVE_FLOCK)
check_function_exists("fork" HAVE_FORK)
check_function_exists("ftime" HAVE_FTIME)
check_function_exists("ftruncate" HAVE_FTRUNCATE)
check_function_exists("getcwd" HAVE_GETCWD)
check_function_exists("geteuid" HAVE_GETEUID)
check_function_exists("getgrent" HAVE_GETGRENT)
check_function_exists("getgroups" HAVE_GETGROUPS)
if(NOT HAVE_GETHOSTBYNAME)
    check_function_exists("gethostbyname" HAVE_GETHOSTBYNAME)
endif()
check_function_exists("gethostent" HAVE_GETHOSTENT)
if(NOT HAVE_GETHOSTNAME)
    check_function_exists("gethostname" HAVE_GETHOSTNAME)
endif()
check_function_exists("getitimer" HAVE_GETITIMER)
check_function_exists("getlogin" HAVE_GETLOGIN)
check_function_exists("getnetbyaddr" HAVE_GETNETBYADDR)
check_function_exists("getnetbyname" HAVE_GETNETBYNAME)
check_function_exists("getnetent" HAVE_GETNETENT)
check_function_exists("getpass" HAVE_GETPASS)
check_function_exists("getpgrp" HAVE_GETPGRP)
check_function_exists("getppid" HAVE_GETPPID)
check_function_exists("getpriority" HAVE_GETPRIORITY)
check_function_exists("getprotoent" HAVE_GETPROTOENT)
check_function_exists("getpwent" HAVE_GETPWENT)
check_function_exists("getservent" HAVE_GETSERVENT)
check_function_exists("gettext" HAVE_GETTEXT)
check_function_exists("gettimeofday" HAVE_GETTIMEOFDAY)
check_function_exists("gmtime_r" HAVE_GMTIME_R)
check_function_exists("hstrerror" HAVE_HSTRERROR)
check_function_exists("iconv" HAVE_ICONV)
check_function_exists("index" HAVE_INDEX)
check_function_exists("inet_aton" HAVE_INET_ATON)
check_function_exists("inet_lnaof" HAVE_INET_LNAOF)
check_function_exists("inet_makeaddr" HAVE_INET_MAKEADDR)
check_function_exists("inet_netof" HAVE_INET_NETOF)
check_function_exists("inet_ntop" HAVE_INET_NTOP)
check_function_exists("inet_pton" HAVE_INET_PTON)
check_function_exists("ioctl" HAVE_IOCTL)
check_function_exists("isblank" HAVE_ISBLANK)
check_function_exists("kill" HAVE_KILL)
check_function_exists("link" HAVE_LINK)
check_function_exists("lstat" HAVE_LSTAT)
check_function_exists("memcpy" HAVE_MEMCPY)
check_function_exists("memmove" HAVE_MEMMOVE)
check_function_exists("mkdir" HAVE_MKDIR)
check_function_exists("mknod" HAVE_MKNOD)
check_function_exists("mkstemp" HAVE_MKSTEMP)
check_function_exists("nice" HAVE_NICE)
check_function_exists("on_exit" HAVE_ON_EXIT)
check_function_exists("pause" HAVE_PAUSE)
check_function_exists("pipe" HAVE_PIPE)
check_function_exists("putenv" HAVE_PUTENV)
check_function_exists("readdir64_r" HAVE_READDIR64_R)
check_function_exists("readdir_r" HAVE_READDIR_R)
check_function_exists("readlink" HAVE_READLINK)
check_function_exists("rename" HAVE_RENAME)
check_function_exists("rindex" HAVE_RINDEX)
check_function_exists("rmdir" HAVE_RMDIR)
if(HAVE_WINSOCK2_H)
    check_symbol_exists(select "winsock2.h" HAVE_SELECT)
endif()
if(NOT HAVE_SELECT)
    check_function_exists("select" HAVE_SELECT)
endif()
check_function_exists("setegid" HAVE_SETEGID)
check_function_exists("seteuid" HAVE_SETEUID)
check_function_exists("setgroups" HAVE_SETGROUPS)
check_function_exists("sethostent" HAVE_SETHOSTENT)
check_function_exists("sethostname" HAVE_SETHOSTNAME)
check_function_exists("setitimer" HAVE_SETITIMER)
check_function_exists("setlocale" HAVE_SETLOCALE)
check_function_exists("setnetent" HAVE_SETNETENT)
check_function_exists("setpgid" HAVE_SETPGID)
check_function_exists("setpriority" HAVE_SETPRIORITY)
check_function_exists("setprotoent" HAVE_SETPROTOENT)
check_function_exists("setpwent" HAVE_SETPWENT)
check_function_exists("setservent" HAVE_SETSERVENT)
check_function_exists("setsid" HAVE_SETSID)
check_function_exists("sigaction" HAVE_SIGACTION)
check_function_exists("siginterrupt" HAVE_SIGINTERRUPT)
check_function_exists("sincos" HAVE_SINCOS)
check_function_exists("socketpair" HAVE_SOCKETPAIR)
check_function_exists("stat64" HAVE_STAT64)
check_function_exists("strchr" HAVE_STRCHR)
check_function_exists("strcmp" HAVE_STRCMP)
check_function_exists("strdup" HAVE_STRDUP)
check_function_exists("strerror" HAVE_STRERROR)
check_function_exists("strftime" HAVE_STRFTIME)
check_function_exists("strncasecmp" HAVE_STRNCASECMP)
check_function_exists("strptime" HAVE_STRPTIME)
check_function_exists("symlink" HAVE_SYMLINK)
check_function_exists("sync" HAVE_SYNC)
check_function_exists("sysconf" HAVE_SYSCONF)
check_function_exists("system" HAVE_SYSTEM)
check_function_exists("tcgetpgrp" HAVE_TCGETPGRP)
check_function_exists("tcsetpgrp" HAVE_TCSETPGRP)
check_function_exists("times" HAVE_TIMES)
check_function_exists("trunc" HAVE_TRUNC)
check_function_exists("truncate" HAVE_TRUNCATE)
check_function_exists("ttyname" HAVE_TTYNAME)
check_function_exists("tzset" HAVE_TZSET)
check_function_exists("uname" HAVE_UNAME)
check_function_exists("unsetenv" HAVE_UNSETENV)
check_function_exists("usleep" HAVE_USLEEP)
check_function_exists("waitpid" HAVE_WAITPID)
check_function_exists("_NSGetEnviron" HAVE__NSGETENVIRON)
check_function_exists("_pipe" HAVE__PIPE)

# 4. Symbol & Struct Member checks
check_symbol_exists(cuserid "stdio.h" HAVE_DECL_CUSERID)
check_symbol_exists(flock "sys/file.h" HAVE_DECL_FLOCK)
check_symbol_exists(hstrerror "sys/socket.h;netdb.h" HAVE_DECL_HSTRERROR)
check_symbol_exists(sethostname "unistd.h" HAVE_DECL_SETHOSTNAME)
check_symbol_exists(strncasecmp "strings.h;string.h" HAVE_DECL_STRNCASECMP)
check_symbol_exists(strptime "time.h" HAVE_DECL_STRPTIME)
check_symbol_exists(tzname "time.h" HAVE_DECL_TZNAME)
check_symbol_exists(unsetenv "stdlib.h" HAVE_DECL_UNSETENV)
check_symbol_exists(vsnprintf "stdio.h" HAVE_DECL_VSNPRINTF)
check_symbol_exists(h_errno "netdb.h" HAVE_H_ERRNO)
check_symbol_exists(isinf "math.h" HAVE_ISINF)
check_symbol_exists(isnan "math.h" HAVE_ISNAN)
check_symbol_exists("struct tm" "sys/time.h;time.h" TM_IN_SYS_TIME)

check_c_source_compiles("
#include <time.h>
int main(void) {
    struct timespec t;
    (void)t;
    return 0;
}
" HAVE_STRUCT_TIMESPEC)

check_struct_has_member("struct stat" st_blksize "sys/stat.h" HAVE_STRUCT_STAT_ST_BLKSIZE)
check_struct_has_member("struct stat" st_blocks "sys/stat.h" HAVE_STRUCT_STAT_ST_BLOCKS)
check_struct_has_member("struct stat" st_rdev "sys/stat.h" HAVE_STRUCT_STAT_ST_RDEV)
check_struct_has_member("struct tm" tm_gmtoff "time.h" HAVE_STRUCT_TM_TM_GMTOFF)
check_struct_has_member("struct tm" tm_zone "time.h" HAVE_STRUCT_TM_TM_ZONE)
check_struct_has_member("struct tm" tm_zone "time.h" HAVE_TM_ZONE)

# 5. Populate SCM_I_GSC_* variables for scmconfig.h.in
macro(SET_SCM_FLAG var cond)
    if(${cond})
        set(${var} 1)
    else()
        set(${var} 0)
    endif()
endmacro()

SET_SCM_FLAG(SCM_I_GSC_NEEDS_STDINT_H HAVE_STDINT_H)
SET_SCM_FLAG(SCM_I_GSC_NEEDS_INTTYPES_H HAVE_INTTYPES_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_LIMITS_H HAVE_LIMITS_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_SYS_TIME_H HAVE_SYS_TIME_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_TIME_H HAVE_TIME_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_STDC_HEADERS HAVE_STDLIB_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_SYS_TYPES_H HAVE_SYS_TYPES_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_SYS_STDTYPES_H HAVE_SYS_STDTYPES_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_SYS_SELECT_H HAVE_SYS_SELECT_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_FLOATINGPOINT_H HAVE_FLOATINGPOINT_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_IEEEFP_H HAVE_IEEEFP_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_NAN_H HAVE_NAN_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_WINSOCK2_H HAVE_WINSOCK2_H)
SET_SCM_FLAG(SCM_I_GSC_HAVE_STRUCT_TIMESPEC HAVE_STRUCT_TIMESPEC)
SET_SCM_FLAG(SCM_I_GSC_HAVE_READDIR64_R HAVE_READDIR64_R)
SET_SCM_FLAG(SCM_I_GSC_HAVE_STAT64 HAVE_STAT64)

if(HAVE_STDINT_H)
    set(SCM_I_GSC_T_INT8 "int8_t")
    set(SCM_I_GSC_T_UINT8 "uint8_t")
    set(SCM_I_GSC_T_INT16 "int16_t")
    set(SCM_I_GSC_T_UINT16 "uint16_t")
    set(SCM_I_GSC_T_INT32 "int32_t")
    set(SCM_I_GSC_T_UINT32 "uint32_t")
    set(SCM_I_GSC_T_INT64 "int64_t")
    set(SCM_I_GSC_T_UINT64 "uint64_t")
    set(SCM_I_GSC_T_INTMAX "intmax_t")
    set(SCM_I_GSC_T_UINTMAX "uintmax_t")
    set(SCM_I_GSC_HAVE_T_INT64 1)
    set(SCM_I_GSC_HAVE_T_UINT64 1)
else()
    set(SCM_I_GSC_T_INT8 "signed char")
    set(SCM_I_GSC_T_UINT8 "unsigned char")
    set(SCM_I_GSC_T_INT16 "short")
    set(SCM_I_GSC_T_UINT16 "unsigned short")
    set(SCM_I_GSC_T_INT32 "int")
    set(SCM_I_GSC_T_UINT32 "unsigned int")
    set(SCM_I_GSC_T_INT64 "long long")
    set(SCM_I_GSC_T_UINT64 "unsigned long long")
    set(SCM_I_GSC_T_INTMAX "long long")
    set(SCM_I_GSC_T_UINTMAX "unsigned long long")
    set(SCM_I_GSC_HAVE_T_INT64 1)
    set(SCM_I_GSC_HAVE_T_UINT64 1)
endif()

if(SIZEOF_INTMAX_T)
    set(SCM_I_GSC_SIZEOF_INTMAX ${SIZEOF_INTMAX_T})
else()
    set(SCM_I_GSC_SIZEOF_INTMAX 8)
endif()

set(SCM_I_GSC_T_PTRDIFF "ptrdiff_t")
if(SIZEOF_PTRDIFF_T)
    set(SCM_I_GSC_SIZEOF_SCM_T_PTRDIFF ${SIZEOF_PTRDIFF_T})
else()
    set(SCM_I_GSC_SIZEOF_SCM_T_PTRDIFF ${SIZEOF_LONG})
endif()

set(SCM_I_GSC_STACK_GROWS_UP 0)
set(STACK_DIRECTION -1)
set(SCM_I_GSC_C_INLINE "inline")
set(SCM_I_GSC_GUILE_DEBUG 0)
set(SCM_I_GSC_GUILE_DEBUG_FREELIST 0)
set(SCM_I_GSC_ENABLE_DISCOURAGED 1)
set(SCM_I_GSC_ENABLE_DEPRECATED 1)
set(SCM_I_GSC_ENABLE_ELISP 1)
set(SCM_I_GSC_HAVE_ARRAYS 1)
set(SCM_I_GSC_HAVE_HOOKS 1)
set(SCM_I_GSC_USE_64_CALLS 1)
set(SCM_I_GSC_USE_NULL_THREADS 1)
set(SCM_I_GSC_USE_PTHREAD_THREADS 0)
set(SCM_I_GSC_NEED_BRACES_ON_PTHREAD_ONCE_INIT 0)
set(SCM_I_GSC_NEED_BRACES_ON_PTHREAD_MUTEX_INITIALIZER 0)
set(SCM_I_GSC_HAVE_STRUCT_DIRENT64 0)

if(WIN32 AND BUILD_SHARED_LIBS)
    set(SCM_I_GSC_USE_DLL_IMPORT 1)
    set(USE_DLL_IMPORT 1)
else()
    set(SCM_I_GSC_USE_DLL_IMPORT 0)
    set(USE_DLL_IMPORT 0)
endif()

if(HAVE_TIME_H AND HAVE_SYS_TIME_H)
    set(TIME_WITH_SYS_TIME 1)
endif()
set(STDC_HEADERS ${HAVE_STDLIB_H})
set(ENABLE_NLS 1)
set(LOCALTIME_CACHE 1)
set(GUILE_USE_64_CALLS 1)
set(HAVE_NETWORKING 1)
set(HAVE_POSIX 1)

# Platform fallback typedefs in config.h if needed
if(NOT HAVE_GETGROUPS)
    set(GETGROUPS_T int)
endif()
if(NOT HAVE_GID_T)
    set(gid_t int)
endif()
if(NOT HAVE_UID_T)
    set(uid_t int)
endif()
if(WIN32)
    set(socklen_t int)
endif()

