/* generated by CMake */
#define SCM_PKGDATA_DIR "@GUILE_PKGDATA_DIR@"
#define SCM_LIBRARY_DIR "@GUILE_LIBRARY_DIR@"
#define SCM_SITE_DIR "@GUILE_SITE_DIR@"
#define SCM_BUILD_INFO { \
	{ "srcdir", "@CMAKE_SOURCE_DIR@" }, \
	{ "top_srcdir", "@CMAKE_SOURCE_DIR@" }, \
	{ "prefix", "@CMAKE_INSTALL_PREFIX@" }, \
	{ "exec_prefix", "@CMAKE_INSTALL_PREFIX@" }, \
	{ "bindir", "@GUILE_BINDIR@" }, \
	{ "sbindir", "@GUILE_SBINDIR@" }, \
	{ "libexecdir", "@GUILE_LIBEXECDIR@" }, \
	{ "datadir", "@GUILE_DATADIR@" }, \
	{ "sysconfdir", "@GUILE_SYSCONFDIR@" }, \
	{ "sharedstatedir", "@GUILE_SHAREDSTATEDIR@" }, \
	{ "localstatedir", "@GUILE_LOCALSTATEDIR@" }, \
	{ "libdir", "@GUILE_LIBDIR@" }, \
	{ "infodir", "@GUILE_INFODIR@" }, \
	{ "mandir", "@GUILE_MANDIR@" }, \
	{ "includedir", "@GUILE_INCLUDEDIR@" }, \
	{ "pkgdatadir", "@GUILE_PKGDATA_DIR@" }, \
	{ "pkglibdir", "@GUILE_PKGLIB_DIR@" }, \
	{ "pkgincludedir", "@GUILE_PKGINCLUDE_DIR@" }, \
	{ "guileversion", "@GUILE_VERSION@" }, \
	{ "libguileinterface", "@LIBGUILE_INTERFACE@" }, \
	{ "LIBS", "@GUILE_LIBS@" }, \
	{ "CFLAGS", "@GUILE_CFLAGS@" }, \
	{ "buildstamp", "@GUILE_BUILDSTAMP@" }, \
}

