<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Writing <TeXmacs> bibliography styles>

  <section|Introduction>

  <TeXmacs> admits support both for <BibTeX> and a native tool for managing
  bibliographies. <BibTeX> styles are denoted by their usual names. <TeXmacs>
  styles are prefixed by <verbatim|tm->. For example, the <TeXmacs>
  <verbatim|<rigid|tm-plain>> style is the replacement for the <BibTeX>
  <verbatim|plain> style. Equivalents for the following <BibTeX> styles have
  been implemented: <verbatim|abbrv>, <verbatim|abstract>, <verbatim|acm>,
  <verbatim|alpha>, <verbatim|elsart-num>, <verbatim|ieeetr>,
  <verbatim|plain>, <verbatim|siam> and <verbatim|unsrt>. These styles can therefore be used without
  installation of <BibTeX>. When <BibTeX> is not installed and a document
  uses a <BibTeX> style <verbatim|<em|name>>, then <TeXmacs> falls back on
  <verbatim|tm-<em|name>>, or on <verbatim|tm-plain> if no such style
  exists.

  New bibliography styles can be defined by the user. Each style is
  associated to a<nbsp>unique <scheme> file, which should be added to the
  directory <verbatim|$TEXMACS_PATH/progs/bibtex>. Style files are treated as
  regular Scheme programs. Since the creation of a style file from scratch is
  a complex task, we recommend you customize existing style files or modules.
  In the next sections, we will describe the creation of a new style on a
  simple example and give a detailed lists of available <scheme> functions
  which facilitate the creation of new styles.

  The bibliography itself is generated by <scm|bib-compile> in
  <verbatim|database/bib-manage.scm>: the cited entries are retrieved from
  the local bibliography, the <verbatim|.bib> files attached to the document
  and the user's bibliographic database, and are passed to the formatting
  routines of the style, which are described below. See <hlink|the <TeXmacs>
  database and bibliographies|../../source/database.en.tm> for the
  underlying machinery.

  <section|Example of a simple bibliography style>

  Bibliographic style files are stored in directory
  <verbatim|$TEXMACS_PATH/progs/bibtex>. They have the name of the style
  followed with extension <verbatim|.scm>. For example,
  <verbatim|example.scm> is the file name associated to the style
  <verbatim|example>, which is denoted by <verbatim|tm-example> when it is
  used in a <TeXmacs> document.

  All style files must be declared as a module as follows:

  <\scm-code>
    (texmacs-module (bibtex example)

    \ \ (:use (bibtex bib-utils) (bibtex plain)))
  </scm-code>

  The module <verbatim|bib-utils> contains all useful functions needed to
  write bibliographic styles; the module of the fall-back style (here
  <verbatim|plain>, see below) should also be used, so that its formatting
  routines are defined.

  All style files must be declared as a bibliographic style as follows:

  <scm-code|(bib-define-style "example" "plain")>

  The first argument to <scm|bib-define-style> is the name of the current
  style. The second argument is the name of a fall-back style,
  <verbatim|plain> in our case. If a function is not defined in current
  style, the function from the fall-back style is used instead. Hence, the
  following minimalistic style file behaves in an identical way as the
  <verbatim|plain> style:

  <\scm-code>
    (texmacs-module (bibtex example)

    \ \ (:use (bibtex bib-utils) (bibtex plain)))

    \;

    (bib-define-style "example" "plain")
  </scm-code>

  Each formatting function defined in the default style can be overloaded in
  the current style. For example, the function <scm|bib-format-date> is used
  to format the date in the <verbatim|plain> style. It is redefinable in our
  example style as follows:

  <\scm-code>
    (tm-define (bib-format-date e)

    \ \ (:mode bib-example?)

    \ \ (bib-format-field e "year"))
  </scm-code>

  All exported functions must be prefixed with <verbatim|bib->. Overloaded
  functions must be followed with directive <scm|(:mode bib-example?)>, in
  which <verbatim|example> is the name of the current style.

  Our complete example file <verbatim|example.scm> is as follows:

  <\scm-code>
    (texmacs-module (bibtex example)

    \ \ (:use (bibtex bib-utils) (bibtex plain)))

    \;

    (bib-define-style "example" "plain")

    \;

    (tm-define (bib-format-date e)

    \ \ (:mode bib-example?)

    \ \ (bib-format-field e "year"))
  </scm-code>

  It behaves in a similar way as the <verbatim|plain> style, except that all
  dates are formatted according to our custom routine.

  Currently, <TeXmacs> only uses its internal styles for the names returned
  by <scm|(bib-standard-styles)>; other style names are passed to
  <BibTeX>. In order to make a new style available, one therefore also has
  to extend this list, for instance in the style file itself or in
  <verbatim|my-init-texmacs.scm>:

  <\scm-code>
    (tm-define (bib-standard-styles)

    \ \ (append (former) (list "tm-example")))
  </scm-code>

  The style module <verbatim|(bibtex example)> is loaded automatically when
  a bibliography with style <verbatim|tm-example> is generated.

  <section|<scheme> functions for writing bibliography styles>

  <subsection|Style management>

  <\explain>
    <scm|(bib-define-style name default)><explain-synopsis|style declaration>
  <|explain>
    This function declares a style called <scm|name> (string) with fall-back
    style <scm|default> (string). The style is selected by choosing
    <verbatim|tm-><scm|name> when adding a bibliography to a document.
    Whenever a<nbsp>formatting function is not defined in the current style,
    its definition in the fall-back style is used as replacement. This macro
    defines a <TeXmacs> mode whose predicate <scm|bib-<scm-arg|name>?> can be
    used in <scm|(:mode ...)> clauses of <scm|tm-define>.
  </explain>

  <\explain>
    <scm|(bib-with-style style fun . args)><explain-synopsis|local style>
  <|explain>
    This function applies the function <scm|fun> to the arguments
    <scm|args> as if the current style were <scm|style> (string), and
    returns the result.
  </explain>

  <subsection|Field related routines>

  <\explain>
    <scm|(bib-field entry field)><explain-synopsis|field data>
  <|explain>
    This function creates a <TeXmacs> tree corresponding to the field
    <scm|field> (string) of entry <scm|entry> without format. In some cases,
    the output is special:

    <\itemize-dot>
      <item>If <scm|field> is <scm|"author"> or <scm|"editor">, we return a
      tree with label <verbatim|bib-names> followed by a list of author
      names; each author name is a tree with label <verbatim|bib-name>
      containing four elements: first name, particule (von), last name and
      suffix (jr);

      <item>If <scm|field> is <scm|"pages">, then we return a tree with label
      <verbatim|bib-pages>, followed by one or two page numbers (as strings)
      corresponding to a single page or a pages interval. If the field
      could not be parsed, then the single page number is <scm|"0">.
    </itemize-dot>
  </explain>

  <\explain>
    <scm|(bib-format-field entry field)><explain-synopsis|basic format>
  <|explain>
    This function creates a <TeXmacs> tree corresponding to the field
    <scm|field> (string) of entry <scm|entry>, with basic format: the first
    letter is put in upper case, except inside <verbatim|keep-case> blocks.
    The empty string is returned if the field is empty or absent. The
    variants <scm|bib-format-field-preserve-case> and
    <scm|bib-format-field-locase-first> respectively preserve the case and
    put the first letter in lower case.
  </explain>

  <\explain>
    <scm|(bib-format-field-Locase entry field)><explain-synopsis|special
    format>
  <|explain>
    This function is similar to <scm|bib-format-field>, but fields are
    formatted in lower case with an upper case letter at the beginning.
  </explain>

  <\explain>
    <scm|(bib-empty? entry field)><explain-synopsis|null-test of a field>
  <|explain>
    This function returns boolean <scm|#t> if the field <scm|field> (string)
    of entry <scm|entry> is empty or absent; it returns <scm|#f> in the other
    cases.
  </explain>

  <subsection|Routines for structuring the output>

  <\explain>
    <scm|(bib-new-block tm)><explain-synopsis|new block>
  <|explain>
    This function creates a <TeXmacs> tree consisting of a block containing
    <TeXmacs> tree <scm|tm>, with its first letter in upper case and a
    period at the end. The variant <scm|bib-new-case-preserved-block> does
    not change the case.
  </explain>

  <\explain>
    <scm|(bib-new-list sep ltm)><explain-synopsis|separated list>
  <|explain>
    This function creates a <TeXmacs> tree which is the concatenation of all
    the elements of list <scm|ltm> separated with <TeXmacs> tree <scm|sep>.
  </explain>

  <\explain>
    <scm|(bib-new-list-spc ltm)><explain-synopsis|blank separated list>
  <|explain>
    This function is equivalent to the evaluation of <scm|(bib-new-list " "
    ltm)>.
  </explain>

  <\explain>
    <scm|(bib-new-sentence ltm)><explain-synopsis|new sentence>
  <|explain>
    This function creates a <TeXmacs> tree corresponding to a sentence
    containing all the elements of list <scm|ltm> separated by commas. Empty
    elements are skipped. The variant <scm|bib-new-case-preserved-sentence>
    does not put the first letter in upper case.
  </explain>

  <subsection|Routines for textual manipulations>

  <\explain>
    <scm|(bib-abbreviate name dot spc)><explain-synopsis|name abbreviation>
  <|explain>
    This function creates a <TeXmacs> tree corresponding to the abbreviation
    of the name contained in <scm|name> <TeXmacs> tree: it retrieves the list
    of first letters of each word, followed by <scm|dot> (<TeXmacs> tree) and
    separated by <scm|spc> (<TeXmacs> tree).
  </explain>

  <\explain>
    <scm|(bib-add-period tm)><explain-synopsis|dot>
  <|explain>
    This function creates a <TeXmacs> tree with a dot at the end of <scm|tm>.
  </explain>

  <\explain>
    <scm|(bib-default-preserve-case tm)>

    <scm|(bib-default-upcase-first tm)><explain-synopsis|default <TeXmacs>
    tree>
  <|explain>
    These functions simplify the <TeXmacs> tree <scm|tm>; the second one
    also puts its first letter in upper case (except inside
    <verbatim|keep-case> blocks). They are used by the
    <scm|bib-format-field> family of routines.
  </explain>

  <\explain>
    <scm|(bib-emphasize tm)><explain-synopsis|italic>
  <|explain>
    This function creates a <TeXmacs> tree corresponding to the italic
    version of <scm|tm>.
  </explain>

  <\explain>
    <scm|(bib-locase tm)><explain-synopsis|lower case>
  <|explain>
    This function creates a <TeXmacs> tree, which is equal to <scm|tm> with
    all letters in lower case, except for those within <verbatim|keep-case>
    blocks.
  </explain>

  <\explain>
    <scm|(bib-prefix tm nbcar)><explain-synopsis|beginning of a <TeXmacs>
    tree>
  <|explain>
    This function returns a string containing the first <scm|nbcar>
    characters of <scm|tm>.
  </explain>

  <\explain>
    <scm|(bib-upcase tm)><explain-synopsis|upper case>
  <|explain>
    This function creates a <TeXmacs> tree, which is equal to <scm|tm> with
    all letters in upper case, except for those within <verbatim|keep-case>
    blocks.
  </explain>

  <\explain>
    <scm|(bib-upcase-first tm)><explain-synopsis|upper case first letter>
  <|explain>
    This function creates a <TeXmacs> tree, which is equal to <scm|tm> with
    its first letter in upper case, except inside <verbatim|keep-case>
    blocks. Similarly, <scm|(bib-locase-first tm)> puts the first letter in
    lower case.
  </explain>

  <subsection|Miscellaneous routines>

  <\explain>
    <scm|(bib-null? v)><explain-synopsis|null-test>
  <|explain>
    This function returns boolean <scm|#t> if value <scm|v> is empty (the
    empty string, the empty list, or a <markup|with> whose body is empty);
    it returns <scm|#f> in the other cases.
  </explain>

  <\explain>
    <scm|(bib-purify tm)><explain-synopsis|flattening of a <TeXmacs> tree>
  <|explain>
    This function returns a string made of all letters of the <TeXmacs> tree
    <scm|tm>.
  </explain>

  <\explain>
    <scm|(bib-simplify tm)><explain-synopsis|simplification of a <TeXmacs>
    tree>
  <|explain>
    This function returns a <TeXmacs> tree corresponding to the
    simplification of <TeXmacs> tree <scm|tm>.
  </explain>

  <\explain>
    <scm|(bib-text-length tm)><explain-synopsis|length of a <TeXmacs> tree>
  <|explain>
    This function returns the length of <TeXmacs> tree <scm|tm>.
  </explain>

  <\explain>
    <scm|(bib-translate msg)><explain-synopsis|translation>
  <|explain>
    This function returns the markup <scm|(localize msg)>, which translates
    the string message <scm|msg> from English into the language of the
    document.
  </explain>

  <\explain>
    <scm|(bib-standard-styles)><explain-synopsis|internal styles>
  <|explain>
    This function returns the list of the names (with the <verbatim|tm->
    prefix) of the styles which are handled by the <scheme> implementation.
  </explain>

  <tmdoc-copyright|2010\U2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<\initial>
  <\collection>
    <associate|preamble|false>
  </collection>
</initial>