/******************************************************************************
 * MODULE     : mac_scroll_phase.h
 * DESCRIPTION: phases of the trackpad scroll gestures (for SDL based GUIs)
 * COPYRIGHT  : (C) 2026  Massimiliano Gubinelli
 *******************************************************************************
 * This software falls under the GNU general public license version 3 or later.
 * It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
 * in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
 ******************************************************************************/

#ifndef MAC_SCROLL_PHASE_H
#define MAC_SCROLL_PHASE_H

// SDL reports the scroll events of a trackpad as wheel events without their
// gesture phase. A local NSEvent monitor sees every scroll event before SDL
// does and records its phase in a queue, from which the GUI takes the phase
// of each wheel event it receives (matched on the deltas). Events without
// deltas are not queued (SDL drops them) but update the finger state.

enum mac_scroll_phase {
  MAC_SCROLL_UNKNOWN= -1,  // no monitor, or not the event we expected
  MAC_SCROLL_WHEEL= 0,     // a mouse wheel (no gesture phase)
  MAC_SCROLL_FINGERS= 1,   // fingers on the trackpad (began, changed)
  MAC_SCROLL_RELEASE= 2,   // the fingers were lifted (ended, cancelled)
  MAC_SCROLL_MOMENTUM= 3   // the momentum scrolling generated by the system
};

void mac_scroll_monitor_start ();
// the phase of the next wheel event with these deltas (SDL's x= -deltaX,
// y= deltaY, possibly flipped): entries which do not match are dropped
int  mac_scroll_phase_pop (double x, double y);
// are fingers currently on the trackpad (scroll gesture in progress)?
bool mac_scroll_fingers_down ();
// true once, when the fingers have been lifted and every queued event of
// the gesture has been popped
bool mac_scroll_take_release ();

#endif // MAC_SCROLL_PHASE_H
