<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Memory and handles>

  <section|The allocator>

  <cpp|tm_new\<less\>C\<gtr\> (args)> obtains memory with <cpp|fast_new>
  and constructs a <cpp|C> in it with placement <cpp|new>;
  <cpp|tm_delete (p)> calls the destructor and gives the memory back with
  <cpp|fast_delete> (<source-link|fast_alloc.hpp:375|src/System/Misc/fast_alloc.hpp:375>).
  The allocator (<source-link|fast_alloc.cpp|src/System/Misc/fast_alloc.cpp>)
  works as follows:

  <\itemize>
    <item>Sizes are rounded up to a multiple of the word length (8 bytes on
    64-bit systems), and <cpp|fast_new> adds one word in front of the
    object in which it stores the size, so that <cpp|fast_delete> knows it.

    <item>Blocks smaller than <cpp|MAX_FAST> (264 bytes on 64-bit systems,
    set by the build) are taken from a free list for their size,
    <cpp|alloc_table[size]>; the first word of a free block points to the
    next one. When the list is empty, the block is cut from the current
    64<nbsp>KB chunk (<cpp|enlarge_malloc>), and a new chunk is obtained
    with <cpp|malloc> when the current one is used up.

    <item>Freed small blocks go back to their free list. Chunks are never
    returned to the system, and a block freed with one size is never reused
    for another, so the memory of <TeXmacs> only shrinks for large blocks,
    which use <cpp|malloc> and <cpp|free> directly.

    <item><cpp|tm_new_array\<less\>C\<gtr\> (n)> stores the number of
    elements in front of the array, so that <cpp|tm_delete_array> can run
    the destructors.
  </itemize>

  With <cpp|DEBUG_ON>, three words are kept in front of each object (the
  size twice and its complement) and a guard value after it, and
  <cpp|fast_delete> reports size mismatches and buffer overflows. With
  <cpp|NO_FAST_ALLOC>, <cpp|tm_new> and friends are plain <cpp|new> and
  <cpp|delete>; this is the configuration to use with <name|AddressSanitizer>
  or <name|Valgrind>, which cannot see inside the free lists. The X11 port
  instead replaces the global <cpp|new> and <cpp|delete> by the fast
  allocator.

  <cpp|mem_used> (<scm|texmacs-memory> in <scheme>) adds the large blocks
  and the used part of the chunks; <cpp|mem_info> prints these numbers.
  Both use <cpp|int> and overflow beyond 2<nbsp>GB.

  <section|Handles and reference counts>

  A type <cpp|T> is usually a <em|handle>: a class with a single member,
  <cpp|T_rep* rep>, generated by the macros of <source-link|basic.hpp|src/Kernel/Abstractions/basic.hpp>.
  The representation class derives from <cpp|concrete_struct> or
  <cpp|abstract_struct>, which contain the reference count. The macros
  define the copy constructor and the assignment, which increment the count
  of the new representation and decrement that of the old one
  (<cpp|INC_COUNT>, <cpp|DEC_COUNT>), the destructor, which decrements and
  deletes the representation when the count reaches 0, and
  <cpp|operator-\<gtr\>>, which gives access to the members of the
  representation.

  <\description-paragraphs>
    <item*|<cpp|CONCRETE (T)>, <cpp|CONCRETE_CODE (T)>>The representation
    is a concrete class, created by the constructors of the handle:
    <cpp|T (args): rep (tm_new\<less\>T_rep\<gtr\> (args)) {}>. A
    <cpp|concrete_struct> starts with a count of 1, which belongs to the
    handle that created it.

    <item*|<cpp|ABSTRACT (T)>, <cpp|ABSTRACT_CODE (T)>>The representation
    is an abstract base class whose subclasses implement the behaviour
    (widgets, commands, boxes, renderers through their own macros, ...).
    The handle has a constructor <cpp|T (T_rep*)> which increments the
    count; an <cpp|abstract_struct> therefore starts with a count of 0,
    and functions return <cpp|tm_new\<less\>sub_rep\<gtr\> (...)> as a
    <cpp|T>. Code which builds such an object without that constructor
    sets the count itself (the <cpp|patch> constructors in
    <source-link|patch.cpp|src/Data/History/patch.cpp> write
    <cpp|rep-\<gtr\>ref_count= 1>).

    <item*|<cpp|CONCRETE_NULL>, <cpp|ABSTRACT_NULL>>The same, but the
    representation may be <cpp|NULL>: the default constructor makes a
    <em|nil> handle, tested with <cpp|is_nil>. Lists, observers, commands
    and widgets are of this kind.

    <item*|<cpp|..._TEMPLATE>, <cpp|..._TEMPLATE_2>>The same for templates
    with one or two parameters (<cpp|array\<less\>T\<gtr\>>,
    <cpp|hashmap\<less\>T,U\<gtr\>>).
  </description-paragraphs>

  <cpp|tree> does not use the macros: its representation can be one of
  three classes and is deleted by <cpp|destroy_tree_rep> according to its
  label (<source-link|tree.cpp:24|src/Kernel/Types/tree.cpp:24>), but the
  principle is the same.

  Consequences of this model:

  <\itemize>
    <item>Copying, passing by value and returning objects is cheap, and
    everything is passed by value. An assignment <cpp|a= b> makes
    <cpp|a> and <cpp|b> share their representation, so an in-place change
    of one (<cpp|b \<less\>\<less\> x>, <cpp|b[i]= y>) is seen through the
    other. <cpp|copy (b)> makes an independent copy, one level deep for most
    types and recursively for trees.

    <item>There is no garbage collector: a cycle of handles is never freed.
    Back pointers are therefore plain C++ pointers, such as the
    <cpp|archiver_rep*> of an undo observer.

    <item>Representations are freed as soon as their last handle goes,
    possibly in the middle of an expression. A plain pointer or reference
    into a representation is only valid while some handle keeps it alive.
  </itemize>

  <section|Errors>

  <cpp|ASSERT (cond, msg)> and <cpp|FAILED (msg)> call <cpp|tm_throw>, since
  <cpp|USE_EXCEPTIONS> is always defined in <source-link|basic.hpp|src/Kernel/Abstractions/basic.hpp>.
  <cpp|tm_throw> prints a crash report with a stack trace on the standard
  output and throws the message as a <cpp|string>. The handlers of key
  presses, mouse events and menu actions catch it, cancel the changes of the
  action (see <hlink|the undo system|undo-archiver.en.tm>) and report the
  error with <cpp|handle_exceptions>; a failure while typesetting replaces
  the document by an empty one (<source-link|edit_typeset.cpp:983|src/Edit/Editor/edit_typeset.cpp:983>).
  The whole mechanism is described in <hlink|fatal errors and crash
  reports|server-startup.en.tm>. Assertions are not compiled out in release
  builds, and they are not cheap: each one that fails builds a full report.

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
