<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Inside the kernel: memory and containers>

  <section|Introduction>

  Every part of <TeXmacs> is written with a handful of home-made types:
  <cpp|string>, <cpp|array>, <cpp|list>, <cpp|tree>, <cpp|hashmap> and a
  few more, all built on the same memory model. <hlink|Basic data
  types|types.en.tm> introduces their interfaces. This chapter explains how
  they work inside, because their behaviour follows from it: how objects
  are allocated and freed, what an assignment shares, how much each
  operation costs, and which references stay valid. The last page lists
  the hazards which follow, several of them checked with small programs.

  The kernel is not thread-safe: reference counts, the allocator and the
  global tables are plain variables, so all these objects must only be used
  from the main thread.

  <section|Overview>

  <\description>
    <item*|Allocation>Small objects come from free lists kept per size by
    <cpp|fast_alloc> (<source-link|System/Misc/fast_alloc.hpp|src/System/Misc/fast_alloc.hpp>);
    <cpp|tm_new> and <cpp|tm_delete> replace <cpp|new> and <cpp|delete>.

    <item*|Handles>Almost every type is a <em|handle>, a pointer to a
    reference counted representation, generated by the macros of
    <source-link|Kernel/Abstractions/basic.hpp|src/Kernel/Abstractions/basic.hpp>.
    Copying a handle shares the representation; the representation is
    deleted when its last handle goes.

    <item*|Containers>Strings and arrays are growable buffers, lists are
    linked cells, trees are labels with an array of children, hash maps are
    arrays of lists; all are handles.

    <item*|Errors><cpp|ASSERT> and <cpp|FAILED> throw a C++ exception which
    the event handlers catch (see <hlink|fatal errors and crash
    reports|server-startup.en.tm>).
  </description>

  <section|Source files>

  <\description-paragraphs>
    <item*|<source-link|System/Misc/fast_alloc.hpp|src/System/Misc/fast_alloc.hpp>,
    <source-link|fast_alloc.cpp|src/System/Misc/fast_alloc.cpp>>The
    allocator and <cpp|tm_new>, <cpp|tm_delete>, <cpp|tm_new_array>,
    <cpp|tm_delete_array>.

    <item*|<source-link|Kernel/Abstractions/basic.hpp|src/Kernel/Abstractions/basic.hpp>,
    <source-link|basic.cpp|src/Kernel/Abstractions/basic.cpp>>Integer types,
    the handle macros, <cpp|ASSERT>, <cpp|FAILED>, debug flags and the hash
    functions of numbers and pointers.

    <item*|<source-link|Kernel/Types/string.hpp|src/Kernel/Types/string.hpp>,
    <source-link|Kernel/Containers/array.hpp|src/Kernel/Containers/array.hpp>,
    <source-link|Kernel/Containers/list.hpp|src/Kernel/Containers/list.hpp>>Strings,
    arrays and lists (the template code is in the <verbatim|.cpp> files,
    which the headers include).

    <item*|<source-link|Kernel/Types/tree.hpp|src/Kernel/Types/tree.hpp>,
    <source-link|Kernel/Types/tree_label.hpp|src/Kernel/Types/tree_label.hpp>>Trees
    and their labels.

    <item*|<source-link|Kernel/Containers/hashmap.hpp|src/Kernel/Containers/hashmap.hpp>,
    <source-link|hashset.hpp|src/Kernel/Containers/hashset.hpp>,
    <source-link|iterator.hpp|src/Kernel/Containers/iterator.hpp>,
    <source-link|rel_hashmap.hpp|src/Kernel/Containers/rel_hashmap.hpp>,
    <source-link|hashfunc.hpp|src/Kernel/Containers/hashfunc.hpp>,
    <source-link|hashtree.hpp|src/Kernel/Containers/hashtree.hpp>>Hash
    tables and their relatives.

    <item*|<source-link|tests/Kernel|tests/Kernel/Containers/hashmap_test.cpp>>Unit
    tests of the containers and types (<name|QtTest>, run with
    <verbatim|ctest> in a <name|CMake> build).
  </description-paragraphs>

  <\traverse>
    <branch|Memory and handles|kernel-memory.en.tm>

    <branch|Strings, arrays, lists, trees and hash tables|kernel-structures.en.tm>

    <branch|Pitfalls|kernel-pitfalls.en.tm>
  </traverse>

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
