<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Pitfalls and known bugs>

  <section|Pitfalls>

  <\itemize>
    <item><em|Loci exist only while typeset.> The registry is filled by
    the typesetter and emptied when a bridge is retypeset or destroyed.
    <scm|id-\<gtr\>trees> therefore returns nothing for a buffer which is
    loaded but has not been typeset, and code which registers a locus and
    looks it up immediately may not find it until the next typesetting.

    <item><em|<scm|id-\<gtr\>trees> returns bodies, not loci.> Use
    <scm|id-\<gtr\>loci> to obtain the <markup|locus> tags.

    <item><em|Loci generated by macros.> When the body of a locus is not
    accessible, its identifier is only registered as
    <verbatim|&<em|name>> (inline loci get a locus box, block loci a
    warning). Code that searches loci by identifier must try both forms, as
    <scm|id-update> does.

    <item><em|Hard identifiers are not persistent.> Identifiers produced by
    <markup|hard-id> depend on memory addresses; they must not be stored
    in documents or used for links between files. Use
    <scm|create-unique-id> for that.

    <item><em|The visited set is global.> It is shared by all buffers and
    never cleared during a session.

    <item><em|Mouse rectangles and identifiers are not matched.> The editor
    collects the identifiers and the outlines under the mouse separately
    (a <verbatim|FIXME> in <cpp|update_mouse_loci>), so all active loci
    under the mouse are highlighted together.

    <item><em|Labels need several passes.> References are only correct
    after the iterations of <cpp|edit_typeset_rep::typeset> have
    converged; a reference read from <scheme> right after an edit may
    still hold the old value.
  </itemize>

  <section|Known bugs>

  <\itemize>
    <item><em|<scm|link-vertices> is shadowed inside
    <source-link|link-edit.scm|TeXmacs/progs/link/link-edit.scm>.> The module defines the public
    <scm|(link-vertices ln)> at line 58 and later a private
    <scm|(link-vertices nr)> at line 146, which replaces it <em|inside the
    module>. Other modules see the right function, but within
    <source-link|link-edit.scm|TeXmacs/progs/link/link-edit.scm>:

    <\itemize>
      <item><scm|link-source> and <scm|link-target> (lines 62-66) fail with
      a type error;

      <item><scm|locus-consider-link?> in <verbatim|simple> mode (line 199)
      calls <scm|link-source> and fails, so <scm|locus-link-types> (and
      thus <menu|Link|Delete link>) breaks in that mode;

      <item><scm|remove-link> in <verbatim|bidirectional> mode (line 221)
      obtains no vertices and therefore never removes the copies of the
      link stored in the other loci.
    </itemize>

    <item><em|Simple mode compares a string with a vertex.> Even with the
    previous bug fixed, <scm|locus-consider-link?> (link-edit.scm, lines
    197-200) compares the locus identifier (a string) with
    <scm|(link-source ln)> (a vertex <verbatim|(id ...)>), which is never
    equal.

    <item><em|The file registry forgets file names.> <scm|registry-add>
    (link-extern.scm, line 61) computes the old names with <verbatim|(and
    (registry-get id) '())>, which is always <verbatim|()>, so each new name
    replaces the previous ones instead of being added.

    <item><em|Project tables are bound once (suspected).> The editor binds
    its <cpp|global_ref>, <cpp|global_aux> and <cpp|global_att> to the
    tables of <cpp|buf-\<gtr\>prj> when it is constructed
    (edit_typeset.cpp, lines 39-42). <cpp|project_attach>
    (new_project.cpp, lines 37-40) changes <cpp|buf-\<gtr\>prj> later without rebinding
    them, so a chapter attached to a project in an open view presumably
    keeps using its old tables until the view is recreated, and the
    references would dangle if the project buffer were closed first. This
    has not been verified at run time.

    <item><em|<scm|navigation-list-first-xtype> works by accident.> It
    returns <scm|(navigation-type fl)> for a <em|list> <scm|fl>
    (link-navigate.scm, line 302); since <scm|navigation-type> is
    <scm|car>, this happens to return the first navigation item, which is
    what the caller expects.
  </itemize>

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
