<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Loci in the typesetter and the editor>

  <section|Registering loci: <cpp|build_locus>>

  Loci are registered when they are typeset, by <cpp|build_locus (env, t,
  ids, col, ref, anchor)> in <verbatim|Typeset/Concat/concat_active.cpp>.
  It is called for inline loci (<cpp|concater_rep::typeset_locus>), for
  loci typeset as atomic boxes (<verbatim|concater.cpp>), for block loci
  (<cpp|bridge_locus_rep::my_typeset>) and for loci in the lazy
  typesetter (<cpp|make_lazy_locus>, <verbatim|Typeset/Line/lazy_typeset.cpp>).
  It expands the body (the last argument) and evaluates the other
  arguments one by one:

  <\description>
    <item*|<verbatim|(id <em|name>)>>If the body is <em|accessible> (it
    comes from the document rather than from a macro definition), the
    locus is registered under <em|name> with <cpp|insert_locus>. Otherwise,
    if the source location of the body can be decoded, the parent of the
    corresponding subtree of the document is registered under
    <verbatim|&<em|name>>, so that the locus can still be
    found (the <scheme> function <scm|id-update> uses both forms).

    <item*|<verbatim|(link <em|type> <em|v1> ...)>>The link is completed
    with an attribute argument <verbatim|(attr ... "secure" <em|flag>)>,
    which records whether the document is secure (see <hlink|scripts and
    security|security-scripts.en.tm>), and registered with
    <cpp|insert_link>. Links are registered even when the body is not
    accessible.

    <item*|<verbatim|(observer <em|name> <em|callback>)>>If the body is
    accessible and the callback is allowed (the document is secure, or
    the callback is declared secure), the body is registered with a
    <scheme> callback (<cpp|insert_locus (id, t, cb)>).
  </description>

  All of this is skipped if there is no current link repository
  (<cpp|env-\<gtr\>link_env> is null), which happens when trees are typeset
  outside an editor, for instance in <hlink|output
  widgets|server-layer-windows.en.tm>. <cpp|build_locus> also returns the
  identifiers in <cpp|ids>, the destination of a <verbatim|url> vertex in
  <cpp|ref> and the name of an <verbatim|id> vertex in <cpp|anchor>, and
  computes the colour <cpp|col> of the locus: <verbatim|visited-color> if
  one of its identifiers or destinations has been visited,
  <verbatim|locus-color> otherwise, subject to the rules described in
  <hlink|the link registry|links-kernel.en.tm>. The return value tells
  whether the body is accessible.

  Since the repository belongs to the bridge being typeset (see
  <hlink|the link registry|links-kernel.en.tm>), the consequences are:

  <\itemize>
    <item>a locus is known only once the part of the document containing
    it has been typeset, so <scm|id-\<gtr\>trees> finds nothing in a buffer
    which has been loaded but never typeset;

    <item>when a part of the document is retypeset, its loci are
    unregistered and registered again;

    <item>a locus whose body is generated by a macro is only found through
    its <verbatim|&> identifier, and block loci with such bodies give the
    warning \PIgnored unaccessible loci\Q.
  </itemize>

  <section|Locus boxes and printed links>

  For an inline locus whose body is not accessible,
  <cpp|typeset_locus> wraps the typeset material, in pieces, in
  <em|locus boxes> (<cpp|locus_box>, <verbatim|change_boxes.cpp>). A locus
  box remembers the identifiers, the <cpp|ref> and the <cpp|anchor>:

  <\itemize>
    <item><cpp|locus_box_rep::loci (x, y, delta, ids, rs)> adds its
    identifiers and its outline to those of the box under the point; this
    is how the editor finds loci which are not visible in the tree;

    <item><cpp|locus_box_rep::post_display> emits a hyperlink
    (<cpp|ren-\<gtr\>href>) and an anchor (<cpp|ren-\<gtr\>anchor>) on the
    renderer, which the <abbr|PDF> renderer turns into clickable links
    and destinations.
  </itemize>

  For accessible loci, links are printed by <cpp|box_rep::display_links>
  (<verbatim|boxes.cpp>), which is called for non-screen renderers only:
  it walks up from the source of a box, looks up the identifiers of each
  subtree with <cpp|get_ids>, and emits an <cpp|href> for every
  <verbatim|hyperlink> whose target is a <verbatim|url>.

  <section|Active loci in the editor>

  The editor keeps two lists of identifiers (<verbatim|edit_interface.hpp>):

  <\description>
    <item*|<cpp|mouse_ids>>Computed by <cpp|update_mouse_loci>
    (<verbatim|edit_mouse.cpp>) when the mouse moves: the identifiers of
    the locus boxes under the mouse (<cpp|eb-\<gtr\>loci>) and of the
    subtree under the mouse and its ancestors (<cpp|get_ids>), filtered by
    the <scheme> functions <scm|link-mouse-ids> (which drops identifiers
    whose only links are of type <verbatim|focus>) and
    <scm|link-active-ids> (which keeps identifiers which admit a link that
    can be followed). The outlines of the corresponding loci and of the
    active ancestors (<scm|link-active-upwards>) are collected in
    <cpp|locus_new_rects> and drawn by the repaint code.

    <item*|<cpp|focus_ids>>Computed by <cpp|update_focus_loci> from the
    cursor position: the active identifiers of the subtree containing the
    cursor and its ancestors.
  </description>

  These lists are used as follows:

  <\itemize>
    <item>a left click (without Shift and without dragging) on an active
    locus calls
    <scm|(link-follow-ids <em|mouse_ids> "click")> instead of moving the
    cursor (<cpp|mouse_select>);

    <item>moving the mouse over an active locus calls
    <scm|(link-follow-ids <em|mouse_ids> "mouse-over")>, which the
    <verbatim|preview-ref> style package uses to show reference previews
    (<scm|preview-reference>);

    <item>after each change of the cursor, the focus, the selection or the
    document (<cpp|apply_changes>, and after each key press),
    <scm|(link-follow-ids <em|focus_ids> "focus")> is called if the
    editor has the keyboard focus.
  </itemize>

  The <scheme> side of these calls is described in <hlink|creating and
  following links from <scheme>|links-scheme.en.tm>.

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
