<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Labels, references and the reference table>

  Labels and references combine two mechanisms: loci, for navigation and
  printed hyperlinks, and the <em|reference table> of the buffer, for the
  numbers and page numbers which are displayed.

  <section|The default macros>

  The macros <markup|label>, <markup|reference>, <markup|pageref>,
  <markup|hlink> and <markup|action> are defined in <c++>
  (<verbatim|Typeset/Env/env_default.cpp>), so they exist in every style:

  <\description>
    <item*|<explain-macro|label|Id>>A locus with identifier
    <verbatim|(hard-id <em|Id>)> and a link <verbatim|(link "anchor" (id
    "#<em|Id>"))>, whose body is a flag and <verbatim|(set-binding <em|Id>
    (value "the-label"))>.

    <item*|<explain-macro|reference|Id>>A locus with identifier
    <verbatim|(hard-id <em|Id>)> and a link <verbatim|(link "hyperlink"
    (id <em|hard-id>) (url "#<em|Id>"))>, whose body is
    <verbatim|(get-binding <em|Id>)>. <markup|pageref> is the same with
    <verbatim|(get-binding <em|Id> 1)>.

    <item*|<explain-macro|hlink|body|destination>>A locus with
    identifier <verbatim|(hard-id <em|body>)> and a <verbatim|hyperlink> to
    <verbatim|(url <em|destination>)>.

    <item*|<explain-macro|action|body|script|...>>A locus with an
    <verbatim|action> link to a script.
  </description>

  <markup|hard-id> (<cpp|edit_env_rep::exec_hard_id>) builds an
  identifier starting with <verbatim|%> from the address of the
  environment and of the expanded argument (and a hash of the argument if
  it is not accessible). Such identifiers are stable while a document is
  open but not across sessions, which is fine for these loci: they are
  only used to make the reference clickable. The style package
  <verbatim|preview-ref> (<verbatim|packages/utilities/preview-ref.ts>)
  redefines <markup|reference> and <markup|pageref> with an additional
  <verbatim|mouse-over> link to the script <scm|preview-reference>, which
  shows the labelled content in a tooltip.

  <section|The reference table>

  <cpp|exec_set_binding> (<verbatim|Typeset/Env/env_exec.cpp>) stores the
  value of a label in the table <cpp|env-\<gtr\>local_ref> as a tuple
  <verbatim|(<em|value> <em|page>)>, keeping the previous page number, and
  appends a third component when the label comes from an included file or
  a part of a project (<verbatim|<em|file>#<em|part>>). The page numbers
  are filled in after page breaking by
  <cpp|typesetter_rep::determine_page_references>, which collects the
  <cpp|tag> boxes created for each <markup|set-binding>.
  <cpp|exec_get_binding> reads <cpp|local_ref>, falling back to
  <cpp|global_ref>, and records missing keys.

  The editor typesets its document repeatedly
  (<cpp|edit_typeset_rep::typeset>) until no key is missing or redefined,
  or until no progress is made, after which the remaining missing and
  redefined keys are reported. Unused entries are removed
  (<cpp|clean_unused>).

  The tables of the environment are <em|references> to tables of the
  buffer data, bound once when the editor is created
  (<cpp|edit_typeset_rep::edit_typeset_rep>):

  <\description>
    <item*|<cpp|local_ref>, <cpp|local_aux>, <cpp|local_att>>the fields
    <cpp|ref>, <cpp|aux> and <cpp|att> of <cpp|buf-\<gtr\>data>, which are
    shared by all views and saved with the document (see <hlink|the
    metadata classes|server-layer-metadata.en.tm>);

    <item*|<cpp|global_ref>, <cpp|global_aux>, <cpp|global_att>>the same
    tables of the project buffer if the buffer belongs to a project, so
    that a chapter sees the labels of the whole book; otherwise a private
    table <cpp|grefs> for references and the buffer's own tables for the
    others.
  </description>

  The table is accessible from <scheme> through the editor glue:
  <scm|get-reference>, <scm|set-reference>, <scm|reset-reference>,
  <scm|list-references> (with a starred variant using the project table),
  <scm|find-references> (the keys whose value is a given string), and
  similarly <scm|get-auxiliary>, <scm|set-auxiliary>,
  <scm|list-auxiliaries> for the auxiliary table (tables of contents,
  bibliographies, indices).

  <section|Jumping to labels>

  <cpp|edit_cursor_rep::search_label (s, local)>
  (<scm|label-\<gtr\>path>) looks for the label in the document tree, then
  in the boxes (<cpp|find_tag>, for labels generated by macros), and, unless
  <cpp|local> is set, uses the third component of the reference table
  entry, or the project, to find the file which contains the label; that
  file is then searched in a passive view. <cpp|go_to_label>
  (<scm|go-to-label>) moves the cursor there, loading the file and
  showing the right part of a project if needed. This is what the
  <verbatim|#<em|Id>> targets of references lead to.

  <section|Tools for references (<verbatim|ref-edit.scm>)>

  <\itemize>
    <item>Searching: <scm|search-labels>, <scm|search-references>,
    <scm|search-citations>, <scm|search-duplicate-labels>,
    <scm|search-broken-references> (references to unknown labels, taking
    the project into account) and <scm|search-broken-citations>, with
    the corresponding navigation commands (<scm|go-to-duplicate-label>,
    <scm|go-to-broken-reference>, ...).

    <item>Inferred references: when a reference is typed with a number
    instead of a key (for instance <verbatim|thm:3> or <verbatim|3> after
    the word \Ptheorem\Q), <scm|number-\<gtr\>label> looks the number up
    in the reference table (<scm|find-references>) and picks the label
    whose environment matches; the key is substituted when the reference
    is validated with return.

    <item>Previews: <scm|ref-preview> builds the tooltip shown by
    <scm|preview-reference>, and a <scm|keyboard-press> extension shows it
    while a reference is being typed.
  </itemize>

  <verbatim|ref-markup.scm> implements the \Psmart\Q references of the
  style packages (<scm|ext-smart-ref>, <scm|ext-typed-ref>), which group
  several keys by type and render them as, for instance, \PTheorems 1 and
  2\Q.

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
