<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|Links, bookmarks and metadata in PDF output>

  <section|Hyperlinks>

  The renderer interface has two methods for links, which only printers
  implement: <cpp|href (dest, x1, y1, x2, y2)> makes the rectangle a link
  to <cpp|dest>, and <cpp|anchor (label, x1, y1, x2, y2)> makes it the
  target of a label. The boxes call them while they are drawn, in two
  ways:

  <\itemize>
    <item>A <markup|locus> whose body is not accessible in the document
    (the body is generated by a macro, as for <markup|reference>,
    <markup|pageref> or <markup|label>) is typeset as a <cpp|locus_box>
    (<source-link|concat_active.cpp:205|src/Typeset/Concat/concat_active.cpp:205>).
    <cpp|build_locus> takes the destination from the <verbatim|(url
    <em|dest>)> vertex of its links (<cpp|ref>), and the anchor from an
    <verbatim|(id <em|name>)> vertex (<cpp|anchor>). The <markup|label>
    macro carries a link <verbatim|(link anchor (id "#<em|name>"))> and
    <markup|reference> a link to <verbatim|(url "#<em|name>")>
    (<source-link|env_default.cpp:381|src/Typeset/Env/env_default.cpp:381>),
    so anchors and internal destinations have the same form. After drawing,
    <cpp|locus_box_rep::post_display> calls <cpp|href> and
    <cpp|anchor> with the box of each word
    (<source-link|change_boxes.cpp:740|src/Typeset/Boxes/Modifier/change_boxes.cpp:740>).

    <item>For accessible bodies, typically <markup|hlink>, nothing is stored
    in the boxes. When a box is drawn on a printer,
    <cpp|box_rep::display_links> (<source-link|boxes.cpp:829|src/Typeset/Boxes/Basic/boxes.cpp:829>)
    walks up the path of the box in the edit tree, looks up the identifiers
    of each subtree and their links in the global link tables, and calls
    <cpp|href> for every link of type <verbatim|hyperlink> with a
    <verbatim|url> vertex. These tables are filled by the typesetting for
    the screen (see <hlink|links, loci and references|links.en.tm>), so
    this only works for a buffer which has been typeset on screen.
  </itemize>

  In both cases each box gets its own link: a link of three words becomes
  three annotations.

  <cpp|href> (<source-link|pdf_hummus_renderer.cpp:2297|src/Plugins/Pdf/pdf_hummus_renderer.cpp:2297>)
  writes a <verbatim|/Link> annotation for the rectangle, slightly
  enlarged. Its border is invisible unless the preference
  <verbatim|locus-on-paper> is <verbatim|preserve>. A destination
  <verbatim|#<em|label>> becomes a named destination
  <verbatim|/label<em|n>>, where <em|n> is the number which
  <cpp|get_label_id> gives to the label; anything else becomes a
  <verbatim|/URI> action with the destination as it is, so relative links
  to other files are written unchanged. The annotations are written by the
  destructor, but registered with the page they belong to through
  <cpp|RegisterAnnotationReferenceForNextPageWrite>.

  <cpp|anchor> records the label, the page and the position just above the
  box; <cpp|flush_dests> writes the dictionary of named destinations,
  each with an <verbatim|/XYZ> view of its page, and the
  <cpp|DestinationsWriter> adds it to the catalog as <verbatim|/Dests>.

  <section|Bookmarks>

  The <abbr|PDF> outline is built from the table of contents. The macros of
  <source-link|std-automatic.ts|TeXmacs/packages/standard/std-automatic.ts>
  which add an entry to the table of contents also call
  <markup|toc-notify> with the kind of the entry
  (<verbatim|toc-strong-1>, <verbatim|toc-strong-2>, <verbatim|toc-1>,
  ..., <verbatim|toc-5>) and its title. <cpp|typeset_toc_notify>
  (<source-link|concat_active.cpp:316|src/Typeset/Concat/concat_active.cpp:316>)
  converts the title to plain text, replacing the <TeX>, <LaTeX> and
  <TeXmacs> logos by their names, and produces an invisible
  <cpp|toc_box>; when this box is drawn, it calls <cpp|toc_entry> with the
  kind and title.

  <cpp|toc_entry> (<source-link|pdf_hummus_renderer.cpp:2355|src/Plugins/Pdf/pdf_hummus_renderer.cpp:2355>)
  turns the kind into a level from 1 (<verbatim|toc-strong-1>, chapters
  in books) to 7 (<verbatim|toc-5>) and records the entry with its page
  and position. <cpp|flush_outlines> and <cpp|recurse> build the tree of
  outline items from this flat list of levels: an entry with a higher
  level than the previous one becomes its child. Each item has a
  <verbatim|/Title> written as a <name|UTF-16> hex string, links to its
  parent and siblings, the number of its descendants (negative, so that
  the items are closed), and a destination on its page.

  <section|Metadata>

  <cpp|set_metadata> stores the title, author and subject passed by
  <cpp|print_doc> (see <hlink|from the menu to the file|pdf-export-path.en.tm>),
  and <cpp|flush_metadata> (<source-link|pdf_hummus_renderer.cpp:2464|src/Plugins/Pdf/pdf_hummus_renderer.cpp:2464>)
  writes them to the information dictionary of the trailer, together with
  <verbatim|/Creator> (<verbatim|TeXmacs <em|version>>),
  <verbatim|/Producer> (the same followed by <verbatim|+ Hummus 4.0>) and
  the creation date. There is no <abbr|XMP> metadata stream, and nothing
  more (keywords, language, tagged structure) is written.

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
