<TeXmacs|2.1.4>

<style|<tuple|tmdoc|english>>

<\body>
  <tmdoc-title|The wallet, system keychains and passwords>

  File names below are relative to <verbatim|src/TeXmacs/progs/>.

  <section|The wallet>

  The wallet is an encrypted table from keys to passphrases, so that the
  user does not have to retype the passphrases of keys and documents. It is
  built on <name|GnuPG> and only available when <scm|supports-gpg?> holds.
  The interface is <source-link|security/wallet/wallet-base.scm|TeXmacs/progs/security/wallet/wallet-base.scm>; the
  implementation is <source-link|security/gpg/gpg-wallet.scm|TeXmacs/progs/security/gpg/gpg-wallet.scm>.

  <paragraph|Storage.>The wallet lives in the directory
  <verbatim|$TEXMACS_HOME_PATH/system/gnupg/wallet>, which is a separate
  <name|GnuPG> home directory. It contains one key pair, generated by
  <scm|gpg-wallet-initialize> with the user name
  <verbatim|__TeXmacs_wallet__> and protected by the <em|wallet
  passphrase>, and the file <verbatim|table.gpg>, the table encrypted for
  that key (<scm|gpg-encrypt-save-object>). The fingerprint of the wallet
  key is kept in the preference <verbatim|gpg wallet key fingerprint>;
  <scm|gpg-wallet-initialized?> checks that the directory, the table and a
  secret key with this fingerprint exist.

  <paragraph|On and off.>When the wallet is <em|on>, the decrypted table is
  held in memory (<scm|gpg-wallet-table>) and every change is written back
  at once, encrypted (<scm|gpg-wallet-set>, <scm|gpg-wallet-delete>).
  <scm|wallet-turn-on> decrypts the table with the wallet passphrase;
  <scm|wallet-turn-off> saves it and forgets it. Both also set the
  preference <verbatim|wallet persistent status>, which records whether the
  user wants the wallet to be on in later sessions.

  <paragraph|Use.>Code which wants a stored passphrase wraps the access in
  the macro <scm|with-wallet> (defined in <source-link|init-texmacs.scm|TeXmacs/progs/init-texmacs.scm>,
  expanded by <scm|expand-with-wallet> in
  <source-link|security/wallet/wallet-menu.scm|TeXmacs/progs/security/wallet/wallet-menu.scm>): if the wallet is
  initialized, should be on persistently, but is off, the body is run after
  the dialog which turns the wallet on; otherwise it is run at once. Then
  <scm|wallet-get>, <scm|wallet-set> and <scm|wallet-delete> do nothing
  (and return <scm|#f>) while the wallet is off. The encryption code stores

  <\itemize>
    <item>under the key <verbatim|("gpg" <em|fingerprint>)> the passphrase
    of a secret key, after a successful decryption, and only if the wallet
    is on persistently (<scm|gpg-try-decrypt>);

    <item>under the key <verbatim|(gpg-buffer-passphrase <em|file>)> the
    passphrase of an encrypted document, for the file and for its autosave
    file (<scm|gpg-set-buffer-passphrase>).
  </itemize>

  <paragraph|Maintenance.><scm|wallet-reinitialize> moves the old wallet
  directory aside, creates a new one with the new passphrase, copies the
  table over and removes the old directory (or moves it back on failure).
  <scm|wallet-destroy> removes the wallet directory. The dialogs and the
  preferences are in <source-link|security/wallet/wallet-menu.scm|TeXmacs/progs/security/wallet/wallet-menu.scm>; they warn
  about passphrases with fewer than 8 characters or without upper case
  letters, lower case letters, digits and symbols, but accept them after a
  second confirmation.

  <section|System keychains>

  On <name|macOS> and <name|Windows>, the wallet passphrase itself can be
  stored in the keychain of the operating system, under the service
  <verbatim|TeXmacs> and the account <verbatim|wallet>
  (<scm|wallet-save-passphrase>, <scm|wallet-load-passphrase>). When the
  user turns the wallet on, <scm|wallet-dialogue-turn-on> first tries the
  passphrase from the keychain and only asks if it is missing or wrong.

  <\description>
    <item*|<name|macOS>><source-link|security/keychain/macos-security.scm|TeXmacs/progs/security/keychain/macos-security.scm>
    runs the system command <verbatim|security -i> and sends it
    <verbatim|add-generic-password>, <verbatim|find-generic-password> or
    <verbatim|delete-generic-password> requests on standard input, so that
    the password is not visible on the command line; error reports show
    <verbatim|********> instead of the password.

    <item*|<name|Windows>><source-link|security/keychain/win-security.scm|TeXmacs/progs/security/keychain/win-security.scm> runs
    the helper <verbatim|$TEXMACS_PATH/bin/winwallet> with the arguments
    <verbatim|ADD>, <verbatim|GET> or <verbatim|RM>, the account and the
    service, and sends the password on standard input.
  </description>

  Both modules define the same functions
  (<scm|system-security-add-generic-password>,
  <scm|system-security-find-generic-password>,
  <scm|system-security-quiet-find-generic-password>,
  <scm|system-security-delete-generic-password>); the right one is loaded
  by <source-link|wallet-menu.scm|TeXmacs/progs/security/wallet/wallet-menu.scm> according to the operating system.

  <section|Passwords and salts>

  <source-link|security/password.scm|TeXmacs/progs/security/password.scm> provides <scm|generate-password n>,
  which returns a random password of <math|n> characters containing at
  least one lower case letter, one upper case letter, one digit and one
  symbol, and <scm|generate-salt>. The characters are drawn with
  <scm|gnutls-random-number> when <name|GnuTLS> is available
  (<scm|supports-gnutls?>), and with the ordinary <scm|random> otherwise;
  salts always come from <scm|gnutls-generate-salt>. The <TeXmacs> server
  uses these functions for the administrator password and for password
  hashes (<source-link|server/server-base.scm|TeXmacs/progs/server/server-base.scm>, see <hlink|the
  server|collab-server.en.tm>).

  <tmdoc-copyright|2026|the <TeXmacs> team>

  <tmdoc-license|Permission is granted to copy, distribute and/or modify this
  document under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation; with no
  Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
  Texts. A copy of the license is included in the section entitled "GNU Free
  Documentation License".>
</body>

<initial|<\collection>
</collection>>
