;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : bibtex-test.scm
;; DESCRIPTION : tests of the BibTeX parser, styles and bibliographies
;; COPYRIGHT   : (C) 2026  Massimiliano Gubinelli
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; The bibliography support of TeXmacs:
;;
;;   - the parser of .bib files (parse_bib in Data/Convert/Bibtex/parsebib.cpp
;;     and bib_parse_fields in Plugins/Bibtex/bibtex_functions.cpp), through
;;     the converter bibtex-document -> bibtex-stree (convert/bibtex);
;;   - the built-ins of the native BibTeX engine (bib-text-length,
;;     bib-prefix, bib-purify, bib-add-period, the changes of case...);
;;   - the styles of the native engine (progs/bibtex: plain, abbrv, alpha,
;;     unsrt), through bib-process, as generate_bibliography calls it;
;;   - the export texmacs-stree -> bibtex-document (bibtexout.scm);
;;   - the bibliography of a document, generated by generate-all-aux from
;;     a .bib file with a tm- style, or loaded from a .bbl file.
;;
;; The converters through the bibliographic database (tmbib, conservative
;; import and export) are not checked: they create a user in the database
;; of the TeXmacs home directory. The sorting of citations is checked by
;; utils/cite/cite-sort-test.scm.
;;
;; The checks state the intended behaviour; the bugs of issue #75 which
;; they would reproduce are left out with a FIXME.

(texmacs-module (check bibtex-test)
  (:use (check check-lib)
        (convert bibtex init-bibtex)
        (bibtex bib-utils) (bibtex plain) (bibtex abbrv)
        (bibtex alpha) (bibtex unsrt)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Helpers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; the parsed document of a .bib string, (!file (document ... (body b)))
(define (bib-doc s) (convert s "bibtex-document" "bibtex-stree"))

;; its body, (document entry ...)
(define (bib-parse s)
  (with d (bib-doc s)
    (and (func? d '!file 1)
         (with b (assoc 'body (cdadr d))
           (and b (cadr b))))))

;; the entries of the body, without the comments
(define (bib-entries s)
  (list-filter (cdr (bib-parse s)) (lambda (x) (func? x 'bib-entry))))

;; the value of the field @f of the first entry of @s
(define (bib-value s f)
  (with e (car (bib-entries s))
    (with l (list-filter (cdr (list-ref e 3))
                         (lambda (x) (== (cadr x) f)))
      (if (null? l) #f (caddr (car l))))))

;; the field names of the first entry of @s
(define (bib-names-of s)
  (map cadr (cdr (list-ref (car (bib-entries s)) 3))))

;; the text of a formatted entry, as read: the spaces of nbsp, the text of
;; localize and of the font changes, without bibitem*, label and newblock
(define (flat x)
  (cond ((string? x) x)
        ((func? x 'nbsp) " ")
        ((or (func? x 'bibitem*) (func? x 'label) (func? x 'newblock)) "")
        ((func? x 'with) (flat (cAr x)))
        ((func? x 'localize 1) (flat (cadr x)))
        ((func? x 'cite 1) (string-append "[" (cadr x) "]"))
        ((pair? x) (apply string-append (map flat (cdr x))))
        (else "")))

(define (first-of tag x)
  ;; the first subtree of @x with the label @tag
  (cond ((func? x tag) x)
        ((pair? x) (or (first-of tag (car x)) (first-of tag (cdr x))))
        (else #f)))

;; the bibliography of the entries of @s in @style, as a list of
;; (label key text), in the order of the bibliography
(define (fmt style s)
  (let* ((r (bib-process "bib" style (bib-parse s)))
         (l (if (func? r 'bib-list 2) (cdr (caddr r)) '())))
    (map (lambda (e)
           (list (cadr (first-of 'bibitem* e))
                 (string-drop (cadr (first-of 'label e)) 4)
                 (flat e)))
         l)))

(define (fmt-text style s) (caddr (car (fmt style s))))
(define (fmt-labels style s) (map car (fmt style s)))
(define (fmt-keys style s) (map cadr (fmt style s)))

;; a TeXmacs bibliography to BibTeX
(define (bib-out t) (convert t "texmacs-stree" "bibtex-document"))

(define (contains? s what)
  (and (string? s) (>= (string-search-forwards what 0 s) 0)))

;; the temporary files go to bibtex-tmp in the temporary directory
(define bibtex-dir
  (string-append (url->system (url-temp-dir)) "/bibtex-tmp"))

(define (tmp-file name)
  (system->url (string-append bibtex-dir "/" name)))

(define (remove-tmp-dir)
  (with d (system->url bibtex-dir)
    (when (url-exists? d)
      (for-each system-remove (url-read-directory d "*"))
      (system-rmdir d))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Parser: entries and fields
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; An entry is (bib-entry type key (document (bib-field name value) ...)):
;; the type and the field names are lower case, the key is kept, values in
;; braces, quotes or bare numbers are text, inner braces protect the case
;; (keepcase), newlines are spaces, the pages are a range and a URL a link.
(define (test-parse-entries)
  (check-group "parse: entries and fields")
  (let ((s (string-append
            "@Article{Knu:84,\n  AUTHOR = {Knuth, Donald E.},\n"
            "  Title = \"The {TeX}book\",\n  year = 1984,\n"
            "  pages = {10--20},\n  note = {a {b {c}} d},\n"
            "  url = {http://x.org/a},\n  abstract = {Line one\n"
            "     line two},\n}")))
    (check= (bib-doc "@misc{k, note = {x}}")
            '(!file (document (style "bibliography")
                              (body (document (bib-entry "misc" "k"
                                      (document (bib-field "note" "x"))))))))
    (check= (map cadr (bib-entries s)) '("article"))
    (check= (map caddr (bib-entries s)) '("Knu:84"))
    (check= (bib-names-of s)
            '("author" "title" "year" "pages" "note" "url" "abstract"))
    ;; the protection goes to the end of the word, as for change.case$
    (check= (bib-value s "title") '(concat "The " (keepcase "TeXbook")))
    (check= (bib-value s "year") "1984")
    (check= (bib-value s "pages") '(bib-pages "10" "20"))
    (check= (bib-value s "note") '(concat "a " (keepcase "b c") " d"))
    (check= (bib-value s "url") '(slink "http://x.org/a"))
    (check= (bib-value s "abstract") "Line one line two")
    (check= (bib-value s "author")
            '(bib-names (bib-name "Donald E." "" "Knuth" ""))))
  ;; a single page, an entry in parentheses, several entries
  (check= (bib-value "@misc{k, pages = {7}}" "pages") '(bib-pages "7"))
  (check= (bib-value "@misc(k, title = \"T\", YEAR = 1999)" "year") "1999")
  (check= (map caddr (bib-entries "@misc{a, title={A}} @book{b, title={B}}"))
          '("a" "b"))
  (check= (map cadr (bib-entries "@misc{a, title={A}} @BOOK{b, title={B}}"))
          '("misc" "book"))
  ;; a field without a value, an empty value
  (check= (bib-value "@misc{k, note = {}, title = {T}}" "title") "T")
  ;; FIXME: #75 item 3, pages which do not start with a digit become
  ;; (bib-pages "0") (bib_field_pages, bibtex_functions.cpp:824), where
  ;; "e1002--e1010" should give (bib-pages "e1002" "e1010").
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Parser: @string and #
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; @string abbreviations are replaced by their value, case-insensitively,
;; # concatenates, and the standard abbreviations of BibTeX are known.
(define (test-parse-strings)
  (check-group "parse: @string and #")
  (check= (bib-value "@string{foo = \"Foo\"} @misc{k, journal = foo}"
                     "journal")
          "Foo")
  (check= (bib-value "@string{foo = \"Foo\"} @misc{k, journal = foo # \" Bar\"}"
                     "journal")
          "Foo Bar")
  (check= (bib-value "@string{foo = {Foo}} @misc{k, journal = \"A \" # foo # {!}}"
                     "journal")
          "A Foo!")
  (check= (bib-value "@string{FOO = \"Foo\"} @misc{k, journal = foo # \"Y\"}"
                     "journal")
          "FooY")
  (check= (bib-value "@String(j = {Jour}) @misc(k, journal = J)" "journal")
          "Jour")
  (check= (bib-value "@misc{k, journal = cacm}" "journal")
          "Communications of the ACM")
  (check= (bib-value "@misc{k, journal = tcs # \", vol\"}" "journal")
          "Theoretical Computer Science, vol")
  ;; an unknown abbreviation alone is kept as its name
  (check= (bib-value "@misc{k, journal = unknown}" "journal") "unknown")
  ;; the @string definitions do not appear in the body
  (check= (length (cdr (bib-parse "@string{foo = \"Foo\"} @misc{k, journal = foo}")))
          1)
  ;; FIXME: #75 item 5, an abbreviation used in a later @string is looked
  ;; up case-sensitively (bib_strings_dict, bibtex_functions.cpp:1045):
  ;; @string{FOO = "Foo"} @string{bar = FOO # "Y"} gives bar = "Y", not "FooY".
  ;; FIXME: #75 item 6, an unknown abbreviation inside a # concatenation
  ;; vanishes silently (bibtex_functions.cpp:1063): journal = unknown # " X"
  ;; gives " X" (trimmed to "X"), where the name is kept when it is alone.
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Parser: comments
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Lines starting with %, @comment entries and text between entries are
;; kept as bib-comment, so that they can be saved back, and are not entries.
(define (test-parse-comments)
  (check-group "parse: comments")
  (let ((b (bib-parse (string-append "% a comment\n@comment{whatever}\n"
                                     "@misc{k5, title = {T}}\nsome text\n"
                                     "@misc{k6, title = {U}}"))))
    (check= (cadr b) '(bib-comment (document (bib-line " a comment"))))
    (check= (caddr b) '(bib-comment (bib-entry "comment" "whatever" (document))))
    (check= (list-ref b 4) '(bib-comment (document "some text")))
    (check= (map car (cdr b))
            '(bib-comment bib-comment bib-entry bib-comment bib-entry)))
  (check= (map caddr (bib-entries "@comment{a, title={A}} @misc{b, title={B}}"))
          '("b"))
  ;; FIXME: #75 item 7, the contents of @preamble are dropped (parsebib.cpp,
  ;; bib_list: tpreamble is never added to the result), where
  ;; @preamble{"\newcommand{\x}{y}"} should give a bib-preamble.
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Parser: accents
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Accented letters in LaTeX form become the letters, in the Cork encoding
;; of TeXmacs strings.
(define (test-parse-accents)
  (check-group "parse: accents")
  (check= (bib-value "@misc{k, note = {Caf{\\'e}}}" "note") "Caf\xe9")
  (check= (bib-value "@misc{k, note = {Caf\\'e}}" "note") "Caf\xe9")
  (check= (bib-value "@misc{k, note = {\\\"{o}}}" "note") "\xf6")
  (check= (bib-value "@misc{k, note = {\\'{E}}}" "note") "\xc9")
  (check= (bib-value "@misc{k, note = {\\`a\\^o\\~n}}" "note") "\xe0\xf4\xf1")
  (check= (bib-value "@misc{k, note = {\\c{c}}}" "note") "\xe7")
  (check= (bib-value "@misc{k, note = {{\\ss}}}" "note") "\xff")
  (check= (bib-value "@misc{k, note = {\\o{}}}" "note") "\xf8")
  (check= (bib-value "@misc{k, author = {G{\\\"o}del, Kurt}}" "author")
          `(bib-names (bib-name "Kurt" "" ,(string-append "G\xf6" "del") ""))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Parser: names
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; The authors and editors are split at "and" into (bib-name first von
;; last jr), in the three forms of BibTeX: "First von Last", "von Last,
;; First" and "von Last, Jr, First"; a braced group is one name.
(define (test-parse-names)
  ;; the names end the values, which are not read past their end (#173)
  (define (names s) (bib-value (string-append "@misc{k, author = {" s "}}")
                               "author"))
  (check-group "parse: names")
  (check= (names "John Smith") '(bib-names (bib-name "John" "" "Smith" "")))
  (check= (names "Smith, John") '(bib-names (bib-name "John" "" "Smith" "")))
  (check= (names "Ludwig van Beethoven")
          '(bib-names (bib-name "Ludwig" "van" "Beethoven" "")))
  (check= (names "Jean de la Fontaine")
          '(bib-names (bib-name "Jean" "de la" "Fontaine" "")))
  (check= (names "van Dam, Andries")
          '(bib-names (bib-name "Andries" "van" "Dam" "")))
  (check= (names "Smith, Jr., John")
          '(bib-names (bib-name "John" "" "Smith" "Jr.")))
  (check= (names "von Neumann, Jr, John")
          '(bib-names (bib-name "John" "von" "Neumann" "Jr")))
  (check= (names "Plato") '(bib-names (bib-name "" "" "Plato" "")))
  (check= (names "{Barnes and Noble}")
          '(bib-names (bib-name "" "" (keepcase "Barnes and Noble") "")))
  (check= (names "A. Zed and B. Bee and others")
          '(bib-names (bib-name "A." "" "Zed" "") (bib-name "B." "" "Bee" "")
                      (bib-name "" "" "others" "")))
  (check= (length (names "A and B and C and D")) 5)
  (check= (bib-value "@misc{k, author = {A. Zed and B. Bee}, year = 2000}"
                     "author")
          '(bib-names (bib-name "A." "" "Zed" "") (bib-name "B." "" "Bee" "")))
  (check= (bib-value "@misc{k, editor = {Ed, E. and Fd, F.}}" "editor")
          '(bib-names (bib-name "E." "" "Ed" "") (bib-name "F." "" "Fd" ""))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Parser: malformed input
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Malformed input does not raise an error: an unterminated entry keeps
;; its fields, text without entries is a comment and an empty file is empty.
(define (test-parse-malformed)
  (check-group "parse: malformed input")
  (check= (bib-entries "@misc{k, title = {x}")
          '((bib-entry "misc" "k" (document (bib-field "title" "x")))))
  (check= (bib-parse "no entry here") '(document (bib-comment (document))))
  (check= (bib-parse "") "")
  (check-true (string? (convert (bib-doc "@misc{k, title = {x}") "bibtex-stree"
                                "bibtex-document")))
  ;; FIXME: #75 item 4, braces are not counted inside "..." values
  ;; (bib_within, parsebib.cpp:83-102): title = "A {"} b", year = 2000
  ;; cuts the entry at the inner quote, and year becomes a comment.
  ;; FIXME: #75 item 10, one field which LaTeX cannot parse disables the
  ;; conversion of the whole file (bib_parse_fields, bibtex_functions.cpp:957):
  ;; with note = {\begin{x}}, author = {Smith, John} stays the string
  ;; "Smith, John" instead of (bib-names (bib-name "John" "" "Smith" "")).
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Built-ins of the engine
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; The BibTeX functions text.length$, text.prefix$, purify$, add.period$,
;; change.case$ and format.name$ (abbreviation), on formatted TeXmacs text.
(define (test-builtins)
  (check-group "built-ins")
  (check= (bib-text-length "abc") 3)
  (check= (bib-text-length "") 0)
  (check= (bib-text-length '(concat "ab" "cd")) 4)
  (check= (bib-text-length '(with "font-shape" "italic" "abc")) 3)
  ;; FIXME: #75 item 1, bib-text-length is 0 for a concat with formatted
  ;; parts (bib_tree_length, bibtex_functions.cpp:692 never returns its
  ;; sum): (concat "ab" (keepcase "Cd")) should be 4.
  (check= (bib-prefix "Smith" 3) "Smi")
  (check= (bib-prefix "Sm" 3) "Sm")
  (check= (bib-prefix '(concat "Sm" "ith") 3) "Smi")
  (check= (bib-prefix "others" 3) "+")
  ;; FIXME: #75 item 2, bib-prefix does not look inside with and keepcase
  ;; and counts bytes (bib_get_prefix, bibtex_functions.cpp:713):
  ;; (with "font-shape" "italic" "Smith") gives "" for "Smi", and "<alpha>bc"
  ;; gives "<" for "<alpha>".
  (check= (bib-purify "abc") "abc")
  (check= (bib-purify '(concat "a" (with "font-shape" "italic" "b")
                               (keepcase "C")))
          "abC")
  (check= (bib-add-period "abc") '(concat "abc" "."))
  (check= (bib-add-period "abc,") "abc.")
  (check= (bib-add-period "abc;") "abc.")
  (check= (bib-add-period "abc.") "abc.")
  (check= (bib-add-period "abc?") "abc?")
  (check= (bib-add-period "abc!") "abc!")
  (check= (bib-add-period "") "")
  (check= (bib-upcase-first "iphone") "Iphone")
  (check= (bib-upcase-first "  abc") "  Abc")
  (check= (bib-upcase-first '(math "x")) '(math "x"))
  (check= (bib-locase-first "ABC") "aBC")
  (check= (bib-locase-first '(concat " " (with "font-shape" "italic" "Abc")))
          '(concat " " (with "font-shape" "italic" "abc")))
  (check= (bib-locase "ABC") "abc")
  (check= (bib-upcase "abc") "ABC")
  (check= (bib-locase '(concat "AB" (keepcase "CD"))) '(concat "ab" "CD"))
  (check= (bib-upcase '(concat "ab" (keepcase "cD"))) '(concat "AB" "cD"))
  (check= (bib-default-upcase-first '(concat "ab" (keepcase "cD")))
          '(concat "ab" "cD"))
  (check= (bib-default-preserve-case '(concat "ab" (keepcase "cD")))
          '(concat "ab" (keepcase "cD")))
  ;; FIXME: #75 item 9, bib-upcase-first changes the letters inside
  ;; keepcase (bib_change_first): (keepcase "iPhone") becomes
  ;; (keepcase "IPhone") instead of staying as it is.
  (check= (bib-abbreviate "John Paul" "." " ") '(concat "J" "." " " "P" "."))
  (check= (bib-abbreviate "Jean-Pierre" "." " ") '(concat "J" "." "-" "P" "."))
  (check= (bib-abbreviate "\xc9mile" "." " ") '(concat "\xc9" "."))
  (let ((e '(bib-entry "misc" "k" (document (bib-field "year" "1999")))))
    (check= (bib-field e "year") "1999")
    (check-true (bib-null? (bib-field e "month")))
    (check-true (bib-empty? e "month"))
    (check-false (bib-empty? e "year")))
  (check-true (bib-null? ""))
  (check-true (bib-null? '()))
  (check-true (bib-null? '(with "font-shape" "italic" "")))
  (check-false (bib-null? "x")))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Formatting of names
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; plain writes the full first names, abbrv their initials; two names are
;; joined by "and", more by commas and ", and", and "others" is "et al".
(define (test-names)
  (define (nm style . l)
    (flat (bib-with-style style bib-format-names `(bib-names ,@l))))
  (define n1 '(bib-name "John" "" "Smith" ""))
  (define n2 '(bib-name "Jane Mary" "" "Doe" ""))
  (define n3 '(bib-name "A." "" "Bee" ""))
  (define n4 '(bib-name "John" "von" "Neumann" "Jr."))
  (define others '(bib-name "" "" "others" ""))
  (check-group "names")
  (check= (nm "plain" n1) "John Smith")
  (check= (nm "plain" n1 n2) "John Smith and Jane Mary Doe")
  (check= (nm "plain" n1 n2 n3) "John Smith, Jane Mary Doe, and A. Bee")
  (check= (nm "plain" n1 others) "John Smith et al")
  (check= (nm "plain" n1 n2 others) "John Smith, Jane Mary Doe et al")
  (check= (nm "plain" n4) "John von Neumann, Jr.")
  (check= (nm "plain" '(bib-name "" "" "Plato" "")) "Plato")
  (check= (nm "abbrv" n1 n2) "J. Smith and J. M. Doe")
  (check= (nm "abbrv" n4) "J. von Neumann, Jr.")
  (check= (nm "abbrv" '(bib-name "Jean-Pierre" "" "Serre" "")) "J.-P. Serre")
  ;; the first names are joined to the last name by non-breaking spaces
  ;; after an initial
  (check= (bib-with-style "plain" bib-format-names '(bib-names (bib-name "A." "" "Bee" "")))
          '(concat (concat "A." (nbsp)) "" "Bee" "")))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Sorting and labels
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define sample-bib
  (string-append
   "@article{z, author={Zed, A. and Bee, B.}, title={T}, journal={J}, year=1999}\n"
   "@article{a, author={Abe, A. and Bee, B. and Cee, C.}, title={U}, journal={J}, year=2001}\n"
   "@article{v, author={van Dam, A.}, title={V}, journal={J}, year=2001}\n"
   "@article{d2, author={Doe, J.}, title={W2}, journal={J}, year=2001}\n"
   "@article{d1, author={Doe, J.}, title={W1}, journal={J}, year=2001}\n"
   "@book{e, editor={Ed, E.}, title={B}, publisher={P}, year=1990}\n"
   "@misc{nk, title={No author}}\n"
   "@misc{m5, author={Aa, A. and Bb, B. and Cc, C. and Dd, D. and Ee, E. and Ff, F.}, year=2002}\n"))

;; plain and alpha sort by the names of the authors (the editors for a
;; book without author, the key without either), then by year and title;
;; unsrt keeps the order of the file. The labels of plain are numbers, those
;; of alpha are made of the last names and the year, with a letter for
;; labels which would be equal, and the first three authors and + for
;; more than four.
(define (test-sorting-labels)
  (check-group "sorting and labels")
  (check= (bib-with-style "plain" bib-sort-key (car (bib-entries sample-bib)))
          "ZED A. BEE B.     1999    T")
  (check= (bib-with-style "plain" bib-sort-key
                          (list-ref (bib-entries sample-bib) 6))
          "nk    No author")
  (check= (fmt-keys "plain" sample-bib) '("m5" "a" "d1" "d2" "e" "nk" "v" "z"))
  (check= (fmt-labels "plain" sample-bib) '("1" "2" "3" "4" "5" "6" "7" "8"))
  (check= (fmt-keys "unsrt" sample-bib) '("z" "a" "v" "d2" "d1" "e" "nk" "m5"))
  (check= (fmt-labels "unsrt" sample-bib) '("1" "2" "3" "4" "5" "6" "7" "8"))
  (check= (fmt-keys "abbrv" sample-bib) (fmt-keys "plain" sample-bib))
  (let ((l (fmt "alpha" sample-bib)))
    (check= (map (lambda (x) (list (cadr x) (car x))) l)
            '(("m5" "ABC+02") ("a" "ABC01") ("d1" "Doe01a") ("d2" "Doe01b")
              ("e" "Ed90") ("nk" "nk") ("v" "vD01") ("z" "ZB99"))))
  (bib-process "bib" "alpha" (bib-parse sample-bib))
  (check= (bib-with-style "alpha" bib-sort-key (car (bib-entries sample-bib)))
          "ZB1999    ZED A. BEE B.     1999    T"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Entry types in the styles
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (one style entry) (fmt-text style entry))

;; Each entry type of plain, as plain.bst writes it: blocks ending with a
;; period, the title of an article in lower case but for its protected
;; part, the title of a book in italics, the page ranges with an en dash
;; (Cork \x15); abbrv only abbreviates the first names and alpha only
;; changes the labels.
(define (test-entry-types)
  (define art (string-append
               "@article{a1, author = {Knuth, Donald E.}, title = {The {TeX}book Thing},"
               " journal = {J. Comp}, year = 1984, volume = 2, number = 3,"
               " pages = {10--20}}"))
  (check-group "entry types")
  (check= (one "plain" art)
          (string-append "Donald E. Knuth. The TeXbook thing. J. Comp, 2(3):10\x15" "20, 1984."))
  (check= (one "abbrv" art)
          (string-append "D. E. Knuth. The TeXbook thing. J. Comp, 2(3):10\x15" "20, 1984."))
  (check= (one "unsrt" art) (one "plain" art))
  (check= (one "alpha" art) (one "plain" art))
  (check= (fmt-labels "alpha" art) '("Knu84"))
  ;; the parts of the formatted article
  (with r (bib-process "bib" "plain" (bib-parse art))
    (check= (car r) 'bib-list)
    (check= (cadr r) "1")
    (check-true (first-of 'bibitem* r))
    (check= (first-of 'label r) '(label "bib-a1"))
    (check= (first-of 'with r) '(with "font-shape" "italic" "J. Comp")))
  ;; another prefix for the labels
  (check= (first-of 'label (bib-process "xyz" "plain" (bib-parse art)))
          '(label "xyz-a1"))
  (check= (one "plain" "@book{b1, author = {Lamport, Leslie}, title = {LaTeX}, publisher = {AW}, year = 1986, address = {Reading}}")
          "Leslie Lamport. LaTeX. AW, Reading, 1986.")
  (check= (one "plain" "@book{bv, author={Doe, J.}, title={Big}, volume=12, series={Series}, publisher={Pub}, year=2011, edition={Third}, month={May}}")
          "J. Doe. Big, volume 12 of Series. Pub, Third edition, May 2011.")
  (check= (one "plain" "@book{e, editor={Ed, E.}, title={B}, publisher={P}, year=1990}")
          "E. Ed, editor. B. P, 1990.")
  (check= (one "plain" "@inproceedings{ip, author={Doe, J.}, title={On Things}, booktitle={Proc. Conf}, editor={Ed, E.}, pages={1--10}, year=2000, address={Paris}, publisher={Pub}}")
          (string-append "J. Doe. On things. In E. Ed, editor, Proc. Conf, pages 1\x15" "10. Paris, 2000. Pub."))
  (check= (one "plain" "@conference{cf, author={Doe, J.}, title={Talk}, booktitle={Conf}, year=2010}")
          "J. Doe. Talk. In Conf. 2010.")
  (check= (one "plain" "@incollection{ic, author={Doe, J.}, title={Chap}, booktitle={Coll}, publisher={Pub}, year=2001, chapter=3, pages={4--5}}")
          (string-append "J. Doe. Chap. In Coll, chapter 3, pages 4\x15" "5. Pub, 2001."))
  ;; a chapter without pages is not followed by a comma (#173)
  (check= (one "plain" "@incollection{ic, author={Doe, J.}, title={Chap}, booktitle={Coll}, publisher={Pub}, year=2001, chapter=3}")
          "J. Doe. Chap. In Coll, chapter 3. Pub, 2001.")
  (check= (one "acm" "@incollection{ic, author={Doe, J.}, title={Chap}, booktitle={Coll}, publisher={Pub}, year=2001, chapter=3}")
          "J. Doe. Chap. In Coll, chapter 3. Pub, 2001.")
  (check= (one "siam" "@incollection{ic, author={Doe, J.}, title={Chap}, booktitle={Coll}, publisher={Pub}, year=2001, chapter=3}")
          "J. Doe. Chap. In Coll, chapter 3. Pub, 2001.")
  (check= (one "plain" "@techreport{tr, author={Doe, J.}, title={Report}, institution={Inst}, number={42}, year=2002}")
          "J. Doe. Report. Technical Report 42, Inst, 2002.")
  (check= (one "plain" "@phdthesis{phd, author={Doe, J.}, title={Thesis}, school={Uni}, year=2003}")
          "J. Doe. Thesis. PhD thesis, Uni, 2003.")
  (check= (first-of 'with (bib-process "bib" "plain" (bib-parse "@phdthesis{phd, author={Doe, J.}, title={Thesis}, school={Uni}, year=2003}")))
          '(with "font-shape" "italic" "Thesis"))
  (check= (one "plain" "@mastersthesis{ms, author={Doe, J.}, title={MThesis}, school={Uni}, year=2004}")
          "J. Doe. Mthesis. Master's thesis, Uni, 2004.")
  (check= (one "plain" "@manual{man, title={Manual}, organization={Org}, edition={Second}, year=2005}")
          "Org. Manual. Org, Second edition, 2005.")
  (check= (one "plain" "@booklet{bk, title={Booklet}, howpublished={Online}, year=2006}")
          "Booklet. Online, 2006.")
  (check= (one "plain" "@inbook{inb, author={Doe, J.}, title={Book}, chapter=2, pages={5--9}, publisher={Pub}, year=2007}")
          (string-append "J. Doe. Book, chapter 2, pages 5\x15" "9. Pub, 2007."))
  (check= (one "plain" "@proceedings{pr, editor={Ed, E. and Fd, F.}, title={Proc}, year=2008, publisher={Pub}, volume=5, series={LNCS}}")
          "E. Ed and F. Fd, editors. Proc, volume 5 of LNCS. Pub, 2008.")
  (check= (one "plain" "@unpublished{un, author={Doe, J.}, title={Draft}, note={In preparation}, year=2009}")
          "J. Doe. Draft. In preparation, 2009.")
  (check= (one "plain" "@misc{m1, author = {Zed, A. and Bee, C. and Cee, D. and others}, title = {misc}, year = 2000, howpublished = {web}}")
          "A. Zed, C. Bee, D. Cee et al. Misc. web, 2000.")
  ;; an unknown type is formatted as misc
  (check= (one "plain" "@weird{wd, author={Doe, J.}, title={Odd}, year=2012}")
          "J. Doe. Odd. 2012.")
  ;; an entry with a crossref cites its parent
  (check= (one "plain" "@article{ar, author={Doe, J.}, title={Crossed}, crossref={pr}, pages={7}}")
          "J. Doe. Crossed. In [pr], page 7.")
  (check= (fmt-labels "alpha" "@inproceedings{ip, author={Doe, J.}, title={T}, booktitle={B}, year=2000}\n@proceedings{pr, editor={Ed, E. and Fd, F.}, title={Proc}, year=2008}")
          '("Doe00" "EF08")))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Export
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; A bibliography (a document of bib-entry) is written back as BibTeX:
;; one field per line, names as "von Last, First, Jr", pages with --,
;; protected text in braces, @string, @preamble and the abbreviations used
;; by the fields; what is written reads back to the same entries.
(define (test-export)
  (check-group "export")
  (let* ((src (string-append
               "@misc{k, title = {Caf{\\'e} {B}ig}, author = {Smith, John and"
               " von Neumann, John and others}, pages = {1--5}, year = 2000}"))
         (out (bib-out (bib-parse src))))
    (check= out
            (string-append
             "@Misc{k,\n"
             "  title        = {Caf{\\'e} {Big}},\n"
             "  author       = {Smith, John and von Neumann, John and others},\n"
             "  pages        = {1--5},\n"
             "  year         = {2000}\n"
             "}\n\n"))
    (check= (bib-parse out) (bib-parse src)))
  ;; a name with a Jr part is written "von Last, Jr, First" (#173)
  (let* ((src "@misc{k, author = {von Neumann, Jr, John and Doe, Jr, }}")
         (out (bib-out (bib-parse src))))
    (check-true (contains? out "{von Neumann, Jr, John and Doe, Jr, }"))
    (check= (bib-value out "author")
            '(bib-names (bib-name "John" "von" "Neumann" "Jr")
                        (bib-name "" "" "Doe" "Jr"))))
  (check= (bib-out '(document (bib-string (document (bib-assign "foo" "Foo")))
                              (bib-preamble (document (bib-latex "\\def\\x{y}")))
                              (bib-entry "misc" "k"
                                (document
                                  (bib-field "journal" (concat (bib-var "foo") " bar"))
                                  (bib-field "pages" (bib-pages "3"))))))
          (string-append "@string{ foo = {Foo} }\n\n"
                         "@preamble{ {\\def\\x{y}} }\n\n"
                         "@Misc{k,\n  journal      = foo # { bar},\n"
                         "  pages        = {3}\n}\n\n"))
  ;; comments are kept
  (check-true (contains? (bib-out (bib-parse "% hello\n@misc{k, title={T}}"))
                         "% hello"))
  ;; a whole document is exported through its body
  (check= (bib-out '(document (TeXmacs "2.1") (style "bibliography")
                              (body (document (bib-entry "misc" "k"
                                        (document (bib-field "title" "T")))))))
          "@Misc{k,\n  title        = {T}\n}\n\n")
  ;; the import as a TeXmacs document has the bibliography style
  (check= (convert "@misc{k, note={x}}" "bibtex-document" "texmacs-stree")
          '(document (style "bibliography")
                     (body (document (bib-entry "misc" "k"
                                       (document (bib-field "note" "x")))))))
  (check= (convert "@misc{k, note={x}}" "bibtex-snippet" "texmacs-stree")
          '(document (bib-entry "misc" "k" (document (bib-field "note" "x")))))
  ;; FIXME: #75 item 8, plain string values are written unescaped
  ;; (bibtex-arg, bibtexout.scm:133): note = {50\%} is saved as {50%},
  ;; which LaTeX reads as a comment, and an accented letter as a raw Cork
  ;; byte, where {50\%} and {\'e} are expected.
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; The bibliography of a document
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define doc-bib
  (string-append
   "@article{knuth, author={Knuth, Donald E.}, title={The Art}, journal={J}, year=1968}\n"
   "@book{lamport, author={Lamport, Leslie}, title={LaTeX}, publisher={AW}, year=1986}\n"
   "@inproceedings{part, author={Doe, J.}, title={Part}, crossref={whole}, pages={1--2}}\n"
   "@proceedings{whole, editor={Ed, E.}, title={Whole}, year=2000}\n"
   "@misc{unused, title={X}}\n"))

(define (doc-tm body)
  (string-append "<TeXmacs|2.1>\n\n<style|generic>\n\n<\\body>\n" body
                 "</body>\n"))

(define (generated-bibliography name text)
  ;; the bibliography generated in the document @name holding @text, as
  ;; the bibliography after Document > Update > All
  (let ((u (tmp-file name))
        (old (current-buffer)))
    (string-save (doc-tm text) u)
    (load-buffer u)
    (switch-to-buffer* u)
    (update-forced)
    (generate-all-aux)
    (update-forced)
    (with r (first-of 'bibliography (tree->stree (buffer-get-body u)))
      (buffer-pretend-saved u)
      (buffer-close u)
      (when (buffer-exists? old) (switch-to-buffer old))
      r)))

(define (bib-items t)
  ;; the (label key) of the items of a generated bibliography
  (with l (first-of 'bib-list t)
    (if (not l) '()
        (map (lambda (e) (list (cadr (first-of 'bibitem* e))
                               (string-drop (cadr (first-of 'label e)) 4)))
             (cdr (caddr l))))))

;; The cited entries of a .bib file next to the document are formatted in
;; the tm- style of the bibliography (the native engine, without the
;; database and without bibtex), with the parent of a crossref, and all of
;; them with nocite *; a .bbl file is used when there is no .bib file.
(define (test-document)
  (check-group "document bibliography")
  (string-save doc-bib (tmp-file "refs.bib"))
  (with b (generated-bibliography "plain.tm"
            "  See <cite|lamport> and <cite|knuth>.\n\n  <\\bibliography|bib|tm-plain|refs>\n  </bibliography>\n")
    (check= (list-head b 4) '(bibliography "bib" "tm-plain" "refs"))
    (check= (bib-items b) '(("1" "knuth") ("2" "lamport")))
    (check= (flat (first-of 'concat (first-of 'bib-list b)))
            "Donald E. Knuth. The art. J, 1968."))
  (with b (generated-bibliography "alpha.tm"
            "  <cite|part> <nocite|lamport>\n\n  <\\bibliography|bib|tm-alpha|refs>\n  </bibliography>\n")
    (check= (bib-items b)
            '(("Doe" "part") ("Ed00" "whole") ("Lam86" "lamport"))))
  (with b (generated-bibliography "all.tm"
            "  <nocite|*>\n\n  <\\bibliography|bib|tm-unsrt|refs>\n  </bibliography>\n")
    (check= (map cadr (bib-items b))
            '("knuth" "lamport" "part" "whole" "unused")))
  (string-save (string-append "\\begin{thebibliography}{1}\n\n"
                              "\\bibitem{knuth}\nD.~Knuth.\n\\newblock The art.\n\n"
                              "\\bibitem[Lam86]{lamport}\nL.~Lamport.\n\n"
                              "\\end{thebibliography}\n")
               (tmp-file "only.bbl"))
  (with b (generated-bibliography "bbl.tm"
            "  <cite|knuth>\n\n  <\\bibliography|bib|plain|only>\n  </bibliography>\n")
    (check= (bib-items b) '(("1" "knuth") ("Lam86" "lamport")))
    (check= (flat (first-of 'concat (first-of 'bib-list b)))
            "D. Knuth. The art."))
  ;; without bibtex, a style of BibTeX is replaced by its tm- version, as
  ;; abstract by tm-abstract, whose labels are the keys
  (set-bibtex-command "tm-no-such-bibtex")
  (with b (generated-bibliography "abstract.tm"
            "  <cite|knuth>\n\n  <\\bibliography|bib|abstract|refs>\n  </bibliography>\n")
    (check= (bib-items b) '(("knuth" "knuth"))))
  (set-bibtex-command (get-preference "bibtex command")))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; The suite
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(tm-define (bibtex-test-failures)
  (check-suite "bibtex")
  (test-parse-entries)
  (test-parse-strings)
  (test-parse-comments)
  (test-parse-accents)
  (test-parse-names)
  (test-parse-malformed)
  (test-builtins)
  (test-names)
  (test-sorting-labels)
  (test-entry-types)
  (test-export)
  (remove-tmp-dir)
  (system-mkdir (system->url bibtex-dir))
  (with r (check-run test-document)
    (when (and (pair? r) (== (car r) 'error))
      (check-report #f "the group" (object->string r))))
  (remove-tmp-dir)
  (check-end))
