#!/bin/sh
# Regenerate fl_boot.h, the boot image of femtolisp embedded in TeXmacs,
# from femtolisp/flisp.boot. To rebuild flisp.boot itself after a change of
# femtolisp/system.lsp or femtolisp/compiler.lsp, see README.
cd "$(dirname "$0")"
{
  echo "/* generated by make-boot-header.sh from femtolisp/flisp.boot */"
  echo "static const unsigned char fl_boot_image[]= {"
  od -An -v -tu1 femtolisp/flisp.boot | awk '{ for (i=1; i<=NF; i++) printf "%s,", $i; printf "\n" }'
  echo "0 };"
  echo "static const unsigned long fl_boot_image_length= sizeof (fl_boot_image) - 1;"
} > fl_boot.h
